import { useRouter } from "expo-router";
import { Check, ChevronRight, Circle, Info, Settings, Target, Trash2 } from "lucide-react-native";
import React, { useMemo } from "react";
import { Alert, Platform, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { ProductCard, SectionLabel, StatusPill } from "@/components/PaidProductUI";
import { Backdrop, Meter, PressCard, Reveal } from "@/components/ui";
import { curriculumModule } from "@/constants/modules";
import { C, GUTTER, T, font, radius } from "@/constants/theme";
import { convertedProgressFacts } from "@/lib/convertedLesson";
import { progressHistoryPresentation } from "@/lib/scoredPracticeHistory";
import { useStore } from "@/providers/store";

export default function ProgressScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { activePracticeSession, completed, convertedLessonProgress, pilotProgress, scoredPracticeHistory, deleteSession } = useStore();
  const evidence = useMemo(
    () => progressHistoryPresentation(scoredPracticeHistory, activePracticeSession?.sharedResult),
    [activePracticeSession?.sharedResult, scoredPracticeHistory],
  );
  const isReturning = evidence.recordCount >= 2;
  const confirmDelete = (id: string, title: string): void => {
    const remove = (): void => { void deleteSession(id); };
    if (Platform.OS === "web") { if (globalThis.confirm?.(`Delete the saved record for “${title}”?`)) remove(); return; }
    Alert.alert("Delete this record?", `The saved record for “${title}” will be removed from this device.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: remove }]);
  };

  return <View style={styles.root}><Backdrop /><ScrollView contentContainerStyle={[styles.scroll, { paddingTop: insets.top + 22, paddingBottom: insets.bottom + 112 }]} showsVerticalScrollIndicator={false}>
    <Reveal><Text style={styles.title}>Progress</Text><Text style={styles.intro}>{isReturning ? "Evidence from the scored practices available on this device." : "Your starting evidence, with every gap left visible."}</Text><PressCard onPress={() => router.push("/settings")} accessibilityLabel="Open Settings" style={styles.settingsLink}><Settings size={16} color={C.purple} /><Text style={styles.settingsText}>Settings</Text></PressCard></Reveal>
    <Reveal index={1}><ProductCard accent style={styles.indexCard}><View style={styles.indexTop}><View><SectionLabel>{isReturning ? "Communication Index" : "Starting profile"}</SectionLabel><View style={styles.valueRow}><Text style={styles.indexValue}>{evidence.indexValue ?? "—"}</Text>{evidence.indexValue !== null ? <Text style={styles.outOf}>/ 100</Text> : null}</View></View><View style={styles.coverage}><Text style={styles.coverageValue}>{evidence.observedCount}</Text><Text style={styles.coverageLabel}>OF 6 SIGNALS{`\n`}OBSERVED</Text></View></View><IndexChart values={evidence.chartValues} /><Text style={styles.indexNote}>{evidence.indexValue === null ? "There is not enough approved evidence for an Index value yet." : "Observed signals only. Unobserved signals are not treated as zero."}</Text><PressCard onPress={() => router.push("/progress/how-it-works")} style={styles.howLink} accessibilityLabel="How the Communication Index works"><Info size={15} color={C.purple} /><Text style={styles.howText}>How this is calculated</Text></PressCard></ProductCard></Reveal>
    <Reveal index={2} style={styles.section}><SectionLabel>Six signals</SectionLabel><View style={styles.signalList}>{evidence.rows.map((row) => { const observed = row.value !== null; return <PressCard key={row.key} onPress={() => router.push(`/progress/dimension/${row.key}`)} accessibilityLabel={`${row.label}. ${row.value ?? "Not observed"}`}><View style={styles.signalRow}><View style={styles.signalHeading}>{observed ? <Check size={15} color={C.sage} strokeWidth={2.8} /> : <Circle size={15} color={C.track} />}<Text style={[styles.signalName, observed && styles.signalObserved]}>{row.label}</Text><Text style={styles.signalValue}>{row.value ?? "Not observed"}</Text><ChevronRight size={16} color={C.dim} /></View>{observed ? <><Meter value={row.value ?? 0} tone={C.purple} height={5} /><Text style={styles.evidenceMeta}>{row.evidenceTurnIds.length} approved evidence reference{row.evidenceTurnIds.length === 1 ? "" : "s"}</Text></> : null}</View></PressCard>; })}</View></Reveal>
    <Reveal index={3}><ProductCard style={styles.focusCard}><Target size={20} color={C.purple} /><View style={styles.focusCopy}><SectionLabel tone={C.purple}>Current focus</SectionLabel><Text style={styles.focusTitle}>{evidence.currentFocus ?? "No evidence-backed focus yet"}</Text><Text style={styles.focusMeta}>{evidence.currentFocus ? "From the latest genuinely scored practice." : "Complete an approved scored rehearsal to establish a focus."}</Text></View></ProductCard></Reveal>
    <Reveal index={4} style={styles.section}><SectionLabel>Lesson milestones</SectionLabel>{convertedLessonProgress.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No completed lesson yet</Text><Text style={styles.emptyBody}>Lesson completion, retry, and saved-version milestones appear here.</Text></View> : <View style={styles.history}>{[...convertedLessonProgress].sort((a, b) => b.completedAt - a.completedAt).map((entry) => <ProductCard key={`${entry.practiceId}:${entry.contentVersion}:${entry.runId}`} style={styles.factCard}><Text style={styles.historyTitle}>When the Point Gets Buried</Text><Text style={styles.historyMeta}>{new Date(entry.completedAt).toLocaleDateString()} · content {entry.contentVersion}</Text>{convertedProgressFacts(entry).map((fact) => <View key={fact} style={styles.factRow}><Check size={15} color={C.sage} strokeWidth={2.8} /><Text style={styles.factText}>{fact}</Text></View>)}</ProductCard>)}</View>}</Reveal>
    <Reveal index={5} style={styles.section}><SectionLabel>Practice record</SectionLabel><View style={styles.stats}><View style={styles.stat}><Text style={styles.statValue}>{evidence.recordCount}</Text><Text style={styles.statLabel}>SCORED PRACTICES</Text></View><View style={styles.statRule} /><View style={styles.stat}><Text style={styles.statValue}>{pilotProgress.length}</Text><Text style={styles.statLabel}>COMPLETED MODULES</Text></View></View>{scoredPracticeHistory.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No Index history yet</Text><Text style={styles.emptyBody}>An Index point appears when Hope has approved evidence from a rehearsal.</Text></View> : <View style={styles.history}>{[...scoredPracticeHistory].sort((a, b) => b.completedAt - a.completedAt).map((entry) => <View key={entry.id} style={styles.historyRow}><View style={styles.historyDot} /><View style={styles.historyCopy}><Text style={styles.historyTitle}>{entry.scenarioTitle ?? (entry.moduleId ? curriculumModule(entry.moduleId)?.name : null) ?? "Scored practice"}</Text><Text style={styles.historyMeta}>{new Date(entry.completedAt).toLocaleDateString()} · {entry.observedSignals.length} of 6 signals observed</Text></View><StatusPill label={`${entry.overallIndex} / 100`} tone="purple" /></View>)}</View>}</Reveal>
    <Reveal index={6} style={styles.section}><SectionLabel>Saved rehearsal records</SectionLabel>{completed.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No saved records yet</Text><Text style={styles.emptyBody}>Completed rehearsal records appear here without retaining full transcript text.</Text></View> : <View style={styles.history}>{completed.map((record) => { const label = record.title ?? "Your conversation"; return <View key={record.id} style={styles.savedRow}><PressCard onPress={() => router.push(`/debrief/${record.id}`)} containerStyle={styles.savedMain} accessibilityLabel={`Open ${label}`}><View style={styles.historyCopy}><Text style={styles.historyTitle}>{label}</Text><Text style={styles.historyMeta}>{new Date(record.endedAt ?? record.startedAt).toLocaleDateString()}</Text></View></PressCard><PressCard onPress={() => confirmDelete(record.id, label)} style={styles.deleteHit} accessibilityLabel={`Delete ${label}`}><Trash2 size={16} color={C.dim} /></PressCard><ChevronRight size={17} color={C.dim} /></View>; })}</View>}</Reveal>
  </ScrollView></View>;
}

function IndexChart({ values }: { values: readonly number[] }) { const slots: readonly (number | null)[] = values.length === 0 ? [null] : values; return <View style={styles.chartWrap}><View style={styles.chart} accessibilityRole="image" accessibilityLabel={values.length === 0 ? "No scored practices" : `Scored practices in completion order: ${values.join(", ")}`} >{slots.map((value, index) => <View key={`${index}-${value ?? "empty"}`} style={styles.chartTrack}>{value === null ? null : <View style={[styles.chartBar, { height: `${value}%` }, index === slots.length - 1 && styles.chartCurrent]} />}</View>)}</View><Text style={styles.chartCaption}>{values.length === 0 ? "No scored practice history yet · 0–100" : `${values.length} scored practice${values.length === 1 ? "" : "s"} · one column per completed scored practice · 0–100`}</Text></View>; }

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg }, scroll: { paddingHorizontal: GUTTER }, title: { fontFamily: font.bold, fontSize: 31, lineHeight: 36, color: C.text }, intro: { ...T.support, marginTop: 9, maxWidth: 330 }, settingsLink: { minHeight: 44, alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 7, marginTop: 8 }, settingsText: { fontFamily: font.semi, fontSize: 13, color: C.purple },
  indexCard: { marginTop: 20 }, indexTop: { flexDirection: "row", justifyContent: "space-between" }, valueRow: { flexDirection: "row", alignItems: "flex-end", gap: 6, marginTop: 8 }, indexValue: { fontFamily: font.bold, fontSize: 50, lineHeight: 54, color: C.purple }, outOf: { ...T.support, paddingBottom: 6 }, coverage: { alignItems: "flex-end" }, coverageValue: { fontFamily: font.semi, fontSize: 28, color: C.text }, coverageLabel: { fontFamily: font.semi, fontSize: 9, lineHeight: 13, letterSpacing: 1, color: C.dim, textAlign: "right" },
  chartWrap: { height: 86, marginTop: 6 }, chart: { height: 58, flexDirection: "row", alignItems: "flex-end", gap: 6 }, chartTrack: { flex: 1, height: "100%", borderRadius: 5, backgroundColor: "rgba(81,40,136,0.07)", overflow: "hidden", justifyContent: "flex-end" }, chartBar: { width: "100%", borderRadius: 5, backgroundColor: "rgba(81,40,136,0.25)" }, chartCurrent: { backgroundColor: C.purple }, chartCaption: { ...T.caption, fontSize: 11, marginTop: 5 }, indexNote: { ...T.caption, paddingTop: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: C.line }, howLink: { minHeight: 44, flexDirection: "row", alignItems: "center", gap: 7, alignSelf: "flex-start" }, howText: { fontFamily: font.semi, fontSize: 13, color: C.purple },
  section: { marginTop: 28, gap: 10 }, signalList: { gap: 8 }, signalRow: { minHeight: 66, borderRadius: radius.md, backgroundColor: "rgba(255,255,255,0.68)", borderWidth: 1, borderColor: C.line, padding: 14 }, signalHeading: { flexDirection: "row", alignItems: "center", gap: 9 }, signalName: { ...T.support, color: C.dim, flex: 1 }, signalObserved: { color: C.text, fontFamily: font.semi }, signalValue: { fontFamily: font.semi, fontSize: 13, color: C.purple }, evidenceMeta: { ...T.caption, fontSize: 11, marginTop: 6 },
  focusCard: { marginTop: 26, flexDirection: "row", alignItems: "flex-start", gap: 12 }, focusCopy: { flex: 1 }, focusTitle: { ...T.title, fontSize: 18, marginTop: 6 }, focusMeta: { ...T.caption, marginTop: 5 }, factCard: { gap: 6 }, factRow: { minHeight: 30, flexDirection: "row", alignItems: "center", gap: 8 }, factText: { ...T.support, color: C.text }, stats: { flexDirection: "row", paddingVertical: 16, borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: C.line }, stat: { flex: 1, alignItems: "center" }, statValue: { fontFamily: font.semi, fontSize: 26, color: C.text }, statLabel: { fontFamily: font.semi, fontSize: 9, letterSpacing: 1, color: C.dim, marginTop: 5 }, statRule: { width: StyleSheet.hairlineWidth, backgroundColor: C.line }, empty: { borderRadius: 20, borderWidth: 1, borderStyle: "dashed", borderColor: C.lineStrong, padding: 18 }, emptyTitle: { ...T.support, fontFamily: font.semi, color: C.text }, emptyBody: { ...T.caption, marginTop: 5 }, history: { gap: 4 }, historyRow: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line }, historyDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: C.purple }, historyCopy: { flex: 1 }, historyTitle: { ...T.support, fontFamily: font.semi, color: C.text }, historyMeta: { ...T.caption, marginTop: 3 }, savedRow: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: 6, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: C.line }, savedMain: { flex: 1 }, deleteHit: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
});
