"""Package exact UTF-8 deck bytes from the pinned handoff ZIP; never local review slices.

Fetch with: curl --fail --location --proto '=https' --proto-redir '=https' \
  --max-time 120 --max-filesize 52428800 \
  https://r2-pub.rork.com/attachments/xo73vo5tbrhku6f68brbr.zip -o /tmp/bysi-approved-authoritative.zip
Run: python3 scripts/package-approved-decks.py /tmp/bysi-approved-authoritative.zip
"""
import hashlib
import json
import pathlib
import re
import sys
import zipfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
ARCHIVE_SHA256 = "62348a014a52c062bbcd691f88b3b77b618a72bf41014b6719b1b0f1de42fd03"
archive = pathlib.Path(sys.argv[1])
assert archive.stat().st_size <= 52_428_800, "Archive too large"
assert hashlib.sha256(archive.read_bytes()).hexdigest() == ARCHIVE_SHA256, "Unapproved archive digest"
paths = re.findall(r'archivePath: "([^"]+)"', (ROOT / "constants/approvedLessons.ts").read_text())
assert len(paths) == len(set(paths)) == 12, "Unexpected launch deck catalog"
sources = {}
digests = {}
comparisons = {}
with zipfile.ZipFile(archive) as zipped:
    entries = zipped.infolist()
    assert len(entries) == len({entry.filename for entry in entries}), "Duplicate archive entry"
    assert sum(entry.file_size for entry in entries) < 100_000_000, "Expanded archive too large"
    for entry in entries:
        path = pathlib.PurePosixPath(entry.filename)
        assert not path.is_absolute() and ".." not in path.parts and "\\" not in entry.filename, "Unsafe archive path"
        assert (entry.external_attr >> 16) & 0o170000 != 0o120000, "Symlink in archive"
        assert not entry.flag_bits & 1, "Encrypted archive entry"
    for path in paths:
        raw = zipped.read(path)  # ZIP CRC checked; no archive paths extracted to disk.
        source = raw.decode("utf-8")
        assert source.encode("utf-8") == raw, "Lossy UTF-8 conversion"
        sources[path] = source
        digests[path] = hashlib.sha256(raw).hexdigest()
        local = ROOT / "assets/lesson-decks" / pathlib.PurePosixPath(path).name
        comparisons[path] = local.exists() and hashlib.sha256(local.read_bytes()).hexdigest() == digests[path]
assert digests["BYSI-Rork-Handoff/decks/M1-L1-Buried-Point.html"] == "aa4f4016888794b8f43139e8defdc01c14c4455476fa47f7d1ebb94cd412bd9e"
output = ROOT / "assets/approved-decks"
output.mkdir(parents=True, exist_ok=True)
asset_index = ["// Generated by scripts/package-approved-decks.py; exact approved bytes live outside JS.",
               "const approvedDeckAssets: Readonly<Record<string, number>> = {"]
for path, source in sources.items():
    name = pathlib.PurePosixPath(path).name
    (output / name).write_bytes(source.encode("utf-8"))
    asset_index.append(f'  {json.dumps(path)}: require("./{name}"),')
asset_index.extend(["};", "export default approvedDeckAssets;", ""])
(output / "index.ts").write_text("\n".join(asset_index))
(output / "manifest.json").write_text(json.dumps({"archiveUrl": "https://r2-pub.rork.com/attachments/xo73vo5tbrhku6f68brbr.zip", "archiveSha256": ARCHIVE_SHA256, "decks": digests}, indent=2) + "\n")
(output / "sources.json").unlink(missing_ok=True)
print(json.dumps({"archiveSha256": ARCHIVE_SHA256, "deckCount": len(sources), "sourceBytes": sum(len(s.encode("utf-8")) for s in sources.values()), "localReviewSliceMatches": comparisons}, indent=2))
