import type { CategoryId, Difficulty, Scenario } from "@/types/convo";

export interface Category {
  id: CategoryId;
  label: string;
  blurb: string;
  accent: string;
}

export const CATEGORIES: Category[] = [
  {
    id: "partner",
    label: "Partner",
    blurb: "The conversations you keep postponing at home",
    accent: "#7B62AC",
  },
  {
    id: "family",
    label: "Family",
    blurb: "Boundaries with the people who knew you first",
    accent: "#63409B",
  },
  {
    id: "work",
    label: "Work",
    blurb: "Raises, burnout, feedback, resignations",
    accent: "#4F6C8F",
  },
  {
    id: "friends",
    label: "Friends",
    blurb: "The unspoken things between you",
    accent: "#6A46A0",
  },
];

export const DIFFICULTY: Record<
  Difficulty,
  { label: string; note: string; behaviour: string }
> = {
  gentle: {
    label: "Gentle",
    note: "They listen, but they still have feelings.",
    behaviour:
      "Stay inside the authored persona and keep resistance light. Raise one honest concern, listen to the answer, and become somewhat easier to move without erasing the scenario’s real tension.",
  },
  steady: {
    label: "Steady",
    note: "They question, defend and make you stay specific.",
    behaviour:
      "Stay inside the authored persona and use moderate resistance. Defend one existing concern, question the learner’s framing, and soften only when the learner stays specific, calm, and concrete.",
  },
  challenging: {
    label: "Challenging",
    note: "They hold firm. Bring clarity and composure.",
    behaviour:
      "Stay inside the authored persona and apply firm resistance to its existing concern. Be harder to move and press for a clearer answer, but never invent blame, threats, old grievances, or aggression the scenario did not authorize.",
  },
};

export const SCENARIOS: Scenario[] = [
  {
    id: "chores",
    category: "partner",
    power: "peer",
    title: "Ask for a fair split of the housework",
    counterpart: "Sam — your partner of four years",
    situation:
      "You have been carrying most of the cooking, laundry and admin for months. You've hinted at it before and nothing changed. Tonight the kitchen is a mess again.",
    persona:
      "Sam works long hours and believes they contribute plenty. Past attempts to talk about the split have turned into a tally of who does more, before the two of you agreed on a plan.",
    goal: "Get a specific, agreed change in who does what — not just an apology.",
    opensWith: "user",
    openingLine:
      "(barely looking up from their phone) Hey. I'll deal with the kitchen tomorrow, I swear.",
    minutes: 7,
  },
  {
    id: "intimacy",
    category: "partner",
    power: "peer",
    title: "Say you feel lonely in the relationship",
    counterpart: "Alex — your partner",
    situation:
      "You live parallel lives: phones, separate rooms, no real conversation in weeks. You feel lonely and you're scared that saying it will sound like an accusation.",
    persona:
      "Alex is not cruel. Past attempts to talk about closeness have moved to schedules and who is busier, before either of you got to the feeling underneath.",
    goal: "Be honest about the loneliness without it turning into a fight about who is busier.",
    opensWith: "user",
    openingLine: "(sitting down) You sounded serious on the phone. What's up?",
    minutes: 8,
  },
  {
    id: "wedding-money",
    category: "partner",
    power: "peer",
    title: "Talk about the money you've been avoiding",
    counterpart: "Jordan — your partner",
    situation:
      "There is debt neither of you mentions. You found a statement and need to open the topic without shaming Jordan.",
    persona:
      "Jordan is embarrassed about money. Past attempts to raise it have turned into jokes, then irritation, before the real numbers came out.",
    goal: "Get the real numbers on the table and agree to look at them together this week.",
    opensWith: "user",
    openingLine: "(laughing) Okay, why do you look like you're about to fire me?",
    minutes: 8,
  },
  {
    id: "mother-boundary",
    category: "family",
    power: "mixed_or_unknown",
    title: "Set a boundary with your mother",
    counterpart: "Your mom",
    counterpartGender: "woman",
    situation:
      "She drops by unannounced, comments on your home and choices, and calls daily. You love her and dread hurting her.",
    persona:
      "Warm, anxious, and fluent in guilt. Past attempts to ask for notice have turned to her sacrifices and hurt feelings, before a workable arrangement was agreed. She is not a villain — she is scared of losing closeness.",
    goal: "Ask her to call before visiting, and hold it when she gets hurt.",
    // She arrives mid-stream with soup and a jab about the hallway, so the user
    // is genuinely responding to something here.
    opensWith: "counterpart",
    openingLine:
      "(cheerful) I brought you soup! Don't say I never think of you. Now, when are you going to do something about that hallway?",
    minutes: 8,
  },
  {
    id: "sibling-caregiving",
    category: "family",
    power: "peer",
    title: "Ask your brother to share the caregiving",
    counterpart: "Chris — your older brother",
    counterpartGender: "man",
    situation:
      "You have done nearly all the hospital visits and paperwork for a parent. Chris lives forty minutes away and is always 'slammed'.",
    persona:
      "Chris genuinely believes he is doing his share. Past attempts to divide the caregiving have turned into a defense of how busy he is, before any task got assigned.",
    goal: "Leave with two specific things Chris will own, with dates.",
    opensWith: "user",
    openingLine: "(on speakerphone, distracted) Yep? Everything okay with Dad?",
    minutes: 7,
  },
  {
    id: "parent-comingclean",
    category: "family",
    power: "mixed_or_unknown",
    title: "Tell your parents you’re moving away",
    counterpart: "Your dad",
    counterpartGender: "man",
    situation:
      "You accepted a job in another city and plan to move this summer. Your dad expected you to stay nearby and be available to the family, and you know he will treat the decision as something he can still change.",
    persona:
      "In past conversations, your dad responds with controlled disappointment. He asks practical questions that are really attempts to reopen the decision, emphasizes what the family will lose, and frames his objections as concern. He softens only when the move is stated warmly and as a settled decision.",
    goal: "Tell him you are moving, hold the decision as final, and discuss staying connected without retreating into a defense of your adulthood.",
    opensWith: "user",
    openingLine: "(putting the paper down) You said you wanted to talk. Go ahead.",
    minutes: 7,
  },
  {
    id: "raise",
    category: "work",
    power: "counterpart_has_more_power",
    title: "Ask for the raise you've earned",
    counterpart: "Priya — your manager",
    counterpartGender: "woman",
    situation:
      "You have taken on scope well beyond your title for a year. Budget season is closing this month.",
    persona:
      "Priya is friendly but budget-constrained. Past conversations about pay have moved to timing, the band, and the next cycle, before a specific number was discussed.",
    goal: "Name a specific number and get a commitment or a dated next step.",
    opensWith: "user",
    openingLine:
      "(smiling) Hey! I've only got fifteen — what did you want to cover?",
    minutes: 8,
  },
  {
    id: "burnout",
    category: "work",
    power: "counterpart_has_more_power",
    title: "Tell your boss you're burned out",
    counterpart: "Daniel — your director",
    counterpartGender: "man",
    situation:
      "You are running on empty and have been quietly compensating for a short-staffed team. You are afraid of looking replaceable.",
    persona:
      "Daniel is well-meaning and overloaded. Past mentions of workload have been met with reassurance and next-quarter plans, before anything came off your plate.",
    goal: "Get a concrete reduction in load this month, not sympathy.",
    opensWith: "user",
    openingLine: "(closing his laptop) You've got my full attention. What's going on?",
    minutes: 8,
  },
  {
    id: "feedback",
    category: "work",
    power: "peer",
    title: "Give hard feedback to someone you like",
    counterpart: "Maya — your teammate",
    counterpartGender: "woman",
    situation:
      "Maya keeps missing handoffs and you have been covering. You're friends outside work, which makes it harder.",
    persona:
      "Maya cares a lot about how she is seen. Past attempts to raise the handoffs have ended in fast apologies and a quiet retreat, before a change was agreed.",
    goal: "Be specific and kind, and land one agreed change.",
    opensWith: "user",
    openingLine: "(grinning) Uh oh, a meeting with no agenda. Am I in trouble?",
    minutes: 6,
  },
  {
    id: "quit",
    category: "work",
    power: "counterpart_has_more_power",
    title: "Resign without burning the bridge",
    counterpart: "Elena — your manager",
    counterpartGender: "woman",
    situation:
      "You have accepted another offer. Elena has invested in you and will take it personally.",
    persona:
      "Elena takes departures personally. Past conversations about your future here have moved from shock to a counter-offer to an appeal about the team, before anything concrete was settled.",
    goal: "Deliver the decision as final, warmly, and agree a handover.",
    opensWith: "user",
    openingLine: "(sitting down) You've been quiet this week. What's on your mind?",
    minutes: 6,
  },
  {
    id: "friend-money",
    category: "friends",
    power: "peer",
    title: "Ask a friend for the money back",
    counterpart: "Tom — a close friend",
    counterpartGender: "man",
    situation:
      "Tom borrowed a meaningful amount eight months ago and has not mentioned it since. You need it back and you hate the awkwardness.",
    persona:
      "Tom is embarrassed about the money. Past mentions have been deflected with humor, then vague promises, before a date was set.",
    goal: "Get a real date and amount agreed, and keep the friendship.",
    opensWith: "user",
    openingLine: "(cheerful) Hey, stranger! Long time. Are we doing Friday or what?",
    minutes: 6,
  },
  {
    id: "friend-drift",
    category: "friends",
    power: "peer",
    title: "Name the distance that's grown between you",
    counterpart: "Nadia — your oldest friend",
    counterpartGender: "woman",
    situation:
      "You canceled the birthday weekend Nadia planned last year and never explained that a family crisis had overwhelmed you. Since then, plans keep falling through and neither of you has named the distance. You miss her and want to repair it.",
    persona:
      "In past conversations, Nadia returns to the canceled birthday weekend and says the silence afterward made the friendship feel less important to you. She stays warm but guarded, minimizes the distance at first, and opens up only if you acknowledge that specific rupture without demanding immediate reassurance.",
    goal: "Acknowledge the canceled birthday weekend, explain without excusing it, and learn whether Nadia is open to rebuilding the friendship.",
    opensWith: "user",
    openingLine: "(hugging you) Okay, this is nice, we never do this. How are you?",
    minutes: 7,
  },
  {
    id: "parenting-disagreement",
    category: "partner",
    power: "peer",
    title: "Disagree about a parenting decision",
    counterpart: "Taylor — your partner",
    situation: "Taylor handled a difficult moment with your child differently than you would have. You want the two of you to agree on what to do next without turning one decision into a verdict on either person’s parenting.",
    persona: "In past conversations, Taylor believes the choice made sense in the moment and hears your concern as second-guessing from someone who was not there. Taylor explains the constraint, defends the intent, and becomes more collaborative only when the conversation stays on the next shared response rather than blame.",
    goal: "Understand what happened, agree on one response for the next similar moment, and avoid attacking Taylor’s judgment or character.",
    opensWith: "user",
    openingLine: "(setting down a cup) You said you wanted to talk about what happened earlier. What’s bothering you?",
  },
  {
    id: "last-minute-plan-change",
    category: "partner",
    power: "peer",
    title: "Push back on a last-minute plan change",
    counterpart: "Casey — your partner",
    situation: "Casey changed a shared weekend plan after you had already rearranged work and childcare. The new plan might be reasonable, but finding out late left you carrying the consequences again.",
    persona: "In past conversations, Casey focuses on why the new plan is necessary and initially minimizes the cost of changing it. Casey points out that plans sometimes move and resists being cast as inconsiderate, but can discuss a better notification and decision rule if you stay specific about this handoff.",
    goal: "Address the impact of this change and agree on how future plan changes will be raised before either person commits the other.",
    opensWith: "user",
    openingLine: "(checking the calendar) I know the timing changed, but this option really does make more sense. What’s the problem?",
  },
  {
    id: "whole-task-ownership",
    category: "partner",
    power: "peer",
    title: "Ask them to own the whole task",
    counterpart: "Morgan — your partner",
    situation: "Morgan completes household steps when you ask, but you still notice the need, plan the work, remind them, and check whether it happened. You want to hand over an entire recurring responsibility rather than assign another isolated chore.",
    persona: "In past conversations, Morgan says helping whenever asked is a fair contribution and does not initially see planning and follow-up as part of the task. Morgan worries that full ownership means being criticized for doing it differently, and needs a clear boundary around the result and when to loop you back in.",
    goal: "Transfer one recurring household responsibility, including planning and follow-through, while agreeing on the conditions that require a handoff back.",
    opensWith: "user",
    openingLine: "(looking puzzled) I do it whenever you ask. What exactly are you saying you need me to take over?",
  },
  {
    id: "phone-attention",
    category: "partner",
    power: "peer",
    title: "Talk about phone attention",
    counterpart: "Riley — your partner",
    situation: "Several evenings have ended with both of you on separate screens, and you feel alone even while sitting together. You want more attention without making Riley’s phone use sound like a moral failure.",
    persona: "In past conversations, Riley says the phone is how they decompress and feels accused whenever the topic is framed as choosing a screen over the relationship. Riley points out your own distracted moments, but can engage with one concrete phone-free ritual if you name the loneliness and avoid keeping score.",
    goal: "Explain the disconnection and agree on one repeatable phone-free time without turning the conversation into a tally of who is worse.",
    opensWith: "user",
    openingLine: "(locking the phone) Okay, I’m listening. You look upset—what’s going on?",
  },
  {
    id: "work-priority-conflict",
    category: "partner",
    power: "peer",
    title: "Decide whose work commitment bends",
    counterpart: "Avery — your partner",
    situation: "You both have important work commitments at the same time, and one of you must cover pickup and the evening routine. Past decisions have quietly treated one career as more flexible than the other.",
    persona: "In past conversations, Avery says this particular commitment has unusually high stakes and starts by explaining why moving it is impossible. Avery becomes defensive if the discussion sounds like a ranking of careers, but will compare concrete consequences and trade future coverage if both jobs are treated as real.",
    goal: "Choose who covers this conflict, name the trade being made, and avoid establishing that the same person’s work always comes second.",
    opensWith: "user",
    openingLine: "(opening the calendar) Mine really can’t move this time. Tell me what you’re dealing with on your side.",
  },
  {
    id: "repair-after-snapping",
    category: "partner",
    power: "peer",
    title: "Repair after you snapped",
    counterpart: "Jordan — your partner",
    situation: "During a rushed handoff this morning, you spoke sharply and said Jordan never pays attention. You regret the attack, but the missed handoff underneath it still needs to be resolved.",
    persona: "In past conversations, Jordan returns to the hurt caused by the absolute statement and expects an apology before discussing logistics. Jordan may use the apology to avoid the original issue if it stays vague, but can return to the handoff when you own the wording without withdrawing the concrete concern.",
    goal: "Acknowledge the hurtful wording, apologize without excuses, and return to one specific change needed for the next handoff.",
    opensWith: "user",
    openingLine: "(quietly) I’m still pretty upset about what you said this morning. What did you want to talk about?",
  },
  {
    id: "decline-family-invitation",
    category: "family",
    power: "mixed_or_unknown",
    title: "Decline a family invitation without over-explaining",
    counterpart: "Lena — your aunt",
    counterpartGender: "woman",
    situation: "Your aunt expects you at a large family gathering that your household cannot attend. In the past, every explanation has become a problem for her to solve until your no turns into a negotiation.",
    persona: "In past conversations, Lena treats attendance as proof of family loyalty and responds to reasons by proposing fixes, rides, different arrival times, or shorter visits. She becomes hurt if the answer sounds cold, but can accept a warm, settled no that does not provide new openings to negotiate.",
    goal: "Decline warmly and clearly, resist negotiating each explanation, and preserve connection without agreeing to attend.",
    opensWith: "user",
    openingLine: "(brightly) I’m putting you down for Saturday. Everyone is finally going to be there this year.",
  },
  {
    id: "parenting-criticism",
    category: "family",
    power: "mixed_or_unknown",
    title: "Respond to criticism of your parenting",
    counterpart: "Your father-in-law",
    counterpartGender: "man",
    situation: "Your father-in-law questions one of your parenting decisions in front of your child. You want to stop the commentary now and set a boundary for future disagreements without debating your entire parenting philosophy.",
    persona: "In past conversations, he says his experience gives him the right to intervene and frames criticism as practical help. He dismisses the first boundary as oversensitivity and cites how he raised his own children, but will back down if the request stays concrete and does not invite a philosophy debate.",
    goal: "End the criticism in front of your child and establish that future concerns must be raised privately with you first.",
    opensWith: "counterpart",
    openingLine: "You’re really going to let that slide? In my day, children knew there were consequences.",
  },
  {
    id: "private-news-boundary",
    category: "family",
    power: "peer",
    title: "Ask family not to share your private news",
    counterpart: "Jamie — your cousin",
    situation: "You told Jamie something personal and asked for privacy, but another relative mentioned it two days later. You want to address the breach and define what requires permission without opening a family-wide investigation.",
    persona: "In past conversations, Jamie admits sharing the information but says one trusted relative did not count as making it public. Jamie feels embarrassed, initially focuses on good intentions, and may ask who told you, but can accept a permission rule if the conversation stays on the breach and future behavior.",
    goal: "Confirm what was shared, explain the impact, and require Jamie to ask before passing along personal information in the future.",
    opensWith: "user",
    openingLine: "(uneasy) You sounded serious in your message. Is this about something I said to the family?",
  },
  {
    id: "change-holiday-tradition",
    category: "family",
    power: "mixed_or_unknown",
    title: "Change a family holiday tradition",
    counterpart: "Your mom",
    counterpartGender: "woman",
    situation: "Your household can no longer spend the entire holiday at your mother’s home, and you plan to create a smaller tradition at home. She sees the old plan as proof that the family still stays together.",
    persona: "In past conversations, your mom hears the change as rejection and immediately lists the effort she makes and the people who will be disappointed. She offers compromises that preserve the old arrangement, but can discuss a shorter visit after the new plan is stated as decided rather than proposed for approval.",
    goal: "Tell her the holiday plan is changing, acknowledge the disappointment, and agree on a limited way to celebrate together.",
    opensWith: "user",
    openingLine: "(sorting recipes) I was just planning the holiday menu. You’re still coming for the whole day, right?",
  },
  {
    id: "family-money-request",
    category: "family",
    power: "peer",
    title: "Say no to a family money request",
    counterpart: "Marcus — your brother",
    counterpartGender: "man",
    situation: "Marcus has asked to borrow money for an urgent expense. You believe the need is real, but lending the amount would put your own household under strain and past loans have damaged trust.",
    persona: "In past conversations, Marcus becomes anxious and ashamed, and he interprets questions as doubt about his character. He explains the urgency, promises repayment, and points to times he supported you, but can hear a respectful no if you do not argue that he should not need the money.",
    goal: "Decline the loan clearly, avoid judging how Marcus got here, and decide whether there is any nonfinancial support you genuinely want to offer.",
    opensWith: "user",
    openingLine: "(speaking quickly) I hate asking, but I’m out of options. I can pay you back next month.",
  },
  {
    id: "request-time-off",
    category: "work",
    power: "counterpart_has_more_power",
    title: "Ask for time off when the team is stretched",
    counterpart: "Dana — your manager",
    situation: "You need several days off next month, but the team is short-staffed and your manager has repeatedly emphasized coverage. You have delayed asking because you expect the staffing problem to become your responsibility.",
    persona: "In past conversations, Dana leads with coverage worries, deadlines, and who is already away. Dana does not deny the request outright, but keeps it vague and asks whether the dates are flexible. A clear request and handoff proposal can produce a decision or a specific decision date.",
    goal: "State the dates clearly and get an approval, denial, or named decision date without apologizing for having a life outside work.",
    opensWith: "user",
    openingLine: "(checking the team calendar) We’re very thin next month. What did you need to discuss?",
  },
  {
    id: "manager-skepticism",
    category: "work",
    power: "counterpart_has_more_power",
    title: "Defend your recommendation to a skeptical manager",
    counterpart: "Morgan — your manager",
    situation: "You are recommending a bolder approach after reviewing the evidence, but Morgan favors the familiar low-risk option. You need to defend the recommendation without flooding the discussion with every supporting detail.",
    persona: "In past conversations, Morgan emphasizes accountability for the outcome and distrusts recommendations that sound more exciting than proven. Morgan challenges one assumption, asks what happens if you are wrong, and pushes for the safe option. Morgan engages when you state one rationale, one risk, and one testable next step.",
    goal: "Make the recommendation clearly, support it with the strongest evidence, and secure a decision or bounded test rather than retreating into caveats.",
    opensWith: "user",
    openingLine: "(leaning back) I read your recommendation. Why shouldn’t we stay with the option we already know?",
  },
  {
    id: "meeting-interruption",
    category: "work",
    power: "peer",
    title: "Get your point back after being interrupted",
    counterpart: "Chris — your teammate",
    situation: "During a planning meeting, Chris interrupts while you are explaining a risk and redirects the group to a different solution. This has happened before, and the meeting is moving on before your point is heard.",
    persona: "In past conversations, Chris moves quickly and focuses on momentum rather than trying to dismiss you. Chris assumes the new idea is the natural next step and keeps talking when others hesitate. A calm, immediate interruption that names the unfinished point will return the floor.",
    goal: "Reclaim the floor without escalating, finish the risk you were naming, and connect it to the decision the group is making.",
    opensWith: "counterpart",
    openingLine: "Right, but I think we’re overcomplicating this. Let’s just move ahead with the vendor option and solve the details later.",
  },
  {
    id: "scope-creep",
    category: "work",
    power: "mixed_or_unknown",
    title: "Push back on expanding scope",
    counterpart: "Avery — your client",
    situation: "Avery has added several requests described as small, while keeping the original deadline and budget. Your team can deliver the original scope or absorb some additions, but not everything at once.",
    persona: "In past conversations, Avery says the additions are implied by the original goal and worries that reopening price or timing signals a lack of partnership. Avery minimizes each request separately and invokes urgency, but will choose priorities when the trade-off is concrete and nonpunitive.",
    goal: "Name the accumulated scope change and get a decision about what moves: features, timeline, or budget.",
    opensWith: "user",
    openingLine: "(sharing the latest notes) These are all pretty small changes. I assumed your team could fold them into the current delivery.",
  },
  {
    id: "price-pushback",
    category: "work",
    power: "mixed_or_unknown",
    title: "Handle price pushback without discounting",
    counterpart: "Jordan — a prospective client",
    situation: "Jordan likes your proposal but says a competitor quoted a lower price. You want to understand the objection and defend the value before deciding whether any change to scope or price makes sense.",
    persona: "In past conversations, Jordan returns to the real lower quote and is also testing whether the first price is firm. Jordan repeats the competitor number, asks for a match, and treats differences as minor until you ask what matters most and connect the price to concrete scope or risk.",
    goal: "Learn what is driving the objection, explain the relevant value difference, and avoid offering an immediate unearned discount.",
    opensWith: "user",
    openingLine: "(turning the proposal around) We like you, but this other quote is significantly lower. Can you match it?",
  },
  {
    id: "unhappy-client",
    category: "work",
    power: "mixed_or_unknown",
    title: "Respond to an unhappy client",
    counterpart: "Riley — your client",
    situation: "A recent delivery missed an expectation Riley believed was agreed. Riley wants an immediate correction, but you need to understand the gap before promising timing or accepting responsibility for work outside the agreement.",
    persona: "In past conversations, Riley arrives feeling exposed internally and speaks impatiently. Riley describes the miss as obvious, asks for a same-day fix, and treats clarification as deflection. Riley will slow down if you acknowledge the impact, summarize the disputed expectation, and offer a concrete investigation step.",
    goal: "Acknowledge the impact, identify the expectation gap, and agree on the next diagnostic step without making a promise you cannot verify.",
    opensWith: "counterpart",
    openingLine: "This isn’t what we agreed to. I need you to tell me right now how you’re fixing it today.",
  },
  {
    id: "decline-friend-invitation",
    category: "friends",
    power: "peer",
    title: "Decline an invitation without inventing an excuse",
    counterpart: "Alex — your friend",
    situation: "Alex invited you to a weekend event you do not want to attend. You value the friendship, but usually invent a complicated excuse because a simple no feels rejecting.",
    persona: "In past conversations, Alex is enthusiastic and assumes hesitation means a logistical problem. Alex offers alternate transport, timing, and sleeping arrangements, then worries that you are pulling away. Alex can accept a warm no when it is direct and includes genuine connection that is not a consolation promise.",
    goal: "Decline honestly and warmly without fabricating a reason, over-explaining, or agreeing to attend out of guilt.",
    opensWith: "user",
    openingLine: "(excited) I found us a place to stay, so the weekend is basically handled. You’re in, right?",
  },
  {
    id: "reconnect-after-silence",
    category: "friends",
    power: "peer",
    title: "Reconnect after months of silence",
    counterpart: "Taylor — an old friend",
    situation: "You left Taylor’s messages unanswered for months, even though the friendship matters to you. You want to reconnect without sending an enormous apology or pretending the silence did not happen.",
    persona: "In past conversations, Taylor is glad to hear from you but cautious about investing again. Taylor makes one light joke about the disappearance, then asks what happened and whether you actually have room for the friendship. Warmth alone is not enough; Taylor needs honest ownership and a realistic next step.",
    goal: "Acknowledge the silence, reconnect without over-defending it, and propose one realistic way to be in each other’s lives again.",
    opensWith: "user",
    openingLine: "(answering cautiously) Hey. It’s been a while. Is everything okay?",
  },
  {
    id: "join-group-conversation",
    category: "friends",
    power: "peer",
    title: "Join a group conversation naturally",
    counterpart: "Casey — a person in the group",
    situation: "You are at a gathering where several people already know each other. You have been standing at the edge of their conversation and want to join without interrupting or waiting silently for someone to rescue you.",
    persona: "In past conversations, Casey is friendly but absorbed in the existing conversation and will not automatically stop to include you. Casey responds when you connect to what was just said, asks a natural follow-up, and then gives you room if you contribute rather than apologizing for entering.",
    goal: "Enter the conversation with one relevant observation or question and participate without forcing attention or apologizing for being there.",
    opensWith: "counterpart",
    openingLine: "So we got completely lost, and then the guide tells us we’ve been walking the wrong direction for an hour.",
  },
  {
    id: "leave-conversation-gracefully",
    category: "friends",
    power: "peer",
    title: "Leave a conversation gracefully",
    counterpart: "Morgan — a person you just met",
    situation: "You have enjoyed talking with Morgan at an event, but the conversation has run its course and you want to speak with other people before leaving. You often stay too long because ending the exchange feels rude.",
    persona: "In past conversations, Morgan is sociable and keeps introducing new topics whenever the conversation slows. Morgan is not trying to trap you and responds well to a clear warm close, but will continue if you use vague signals such as looking around or saying you should probably mingle sometime.",
    goal: "Close the conversation warmly, state what you are doing next, and leave without inventing an emergency or waiting for permission.",
    opensWith: "user",
    openingLine: "(smiling) Anyway, that reminds me of another project I worked on last year—have you got a minute?",
  },
  {
    id: "forgotten-name",
    category: "friends",
    power: "peer",
    title: "Recover after forgetting someone’s name",
    counterpart: "Jamie — a person you have met before",
    situation: "Jamie greets you warmly and clearly remembers your previous conversation, but you cannot recall their name. You want to handle the awkwardness directly instead of pretending until someone else says it.",
    persona: "In past conversations, Jamie is friendly and mildly amused. Jamie notices if you avoid using a name and may reference the previous meeting, but does not shame you. A straightforward admission earns an easy reminder; elaborate guessing or pretending makes the moment more uncomfortable.",
    goal: "Acknowledge that you forgot the name, ask for it directly, and continue the conversation without turning the mistake into a performance.",
    opensWith: "counterpart",
    openingLine: "Hey! It’s great to see you again. How did that presentation end up going?",
  },
];

export function scenariosFor(category: CategoryId): Scenario[] {
  return SCENARIOS.filter((s) => s.category === category);
}
