// Generated by scripts/package-approved-decks.py; exact approved bytes live outside JS.
const approvedDeckAssets: Readonly<Record<string, number>> = {
  "BYSI-Rork-Handoff/decks/M1-L1-Buried-Point.html": require("./M1-L1-Buried-Point.html"),
  "BYSI-Rork-Handoff/decks/M1-L2-Cut-the-Case.html": require("./M1-L2-Cut-the-Case.html"),
  "BYSI-Rork-Handoff/decks/M1-L3-Park-and-Return.html": require("./M1-L3-Park-and-Return.html"),
  "BYSI-Rork-Handoff/decks/M1-L4-Make-It-Repeatable.html": require("./M1-L4-Make-It-Repeatable.html"),
  "BYSI-Rork-Handoff/decks/M1-L5-Fit-in-One.html": require("./M1-L5-Fit-in-One.html"),
  "BYSI-Rork-Handoff/decks/M1-Close.html": require("./M1-Close.html"),
  "BYSI-Rork-Handoff/decks/M2-L1-Clear-Ask.html": require("./M2-L1-Clear-Ask.html"),
  "BYSI-Rork-Handoff/decks/M2-L2-Say-Who.html": require("./M2-L2-Say-Who.html"),
  "BYSI-Rork-Handoff/decks/M2-L3-When-They-Say-They-Cant.html": require("./M2-L3-When-They-Say-They-Cant.html"),
  "BYSI-Rork-Handoff/decks/M2-L4-Say-Whether-No.html": require("./M2-L4-Say-Whether-No.html"),
  "BYSI-Rork-Handoff/decks/M2-L5-Ask-for-the-Loop.html": require("./M2-L5-Ask-for-the-Loop.html"),
  "BYSI-Rork-Handoff/decks/M2-Close.html": require("./M2-Close.html"),
};
export default approvedDeckAssets;
