import { mock } from 'bun:test';
import assert from 'node:assert/strict';
import React from 'react';
import { verifyComponentTestDeps } from '../scripts/component-test-deps';
const {create,act}=await import(verifyComponentTestDeps());
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
const Host=(p:any)=>React.createElement('view',p,p.children);
const data=new Map<string,string>();let failedKey='';
const storage={getItem:async(k:string)=>data.get(k)??null,setItem:async(k:string,v:string)=>{if(k===failedKey)throw Error('disk write failure');data.set(k,v);},removeItem:async(k:string)=>{data.delete(k);}};
mock.module('@react-native-async-storage/async-storage',()=>({default:storage}));
mock.module('react-native',()=>({View:Host,Text:Host,ActivityIndicator:Host,StyleSheet:{create:(s:any)=>s},Linking:{openURL:async()=>{}}}));
mock.module('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:59,bottom:34})}));
mock.module('@/constants/theme',()=>({C:{bg:'field'},T:{body:{}}}));
mock.module('@/components/ui',()=>({Backdrop:Host}));
let ui:any;const Button=(p:any)=>React.createElement('button',p);
mock.module('@/components/AnswerFirstOnboarding',()=>({AnswerFirstOnboarding:(p:any)=>{ui=p;return <Host/>;},AnswerButton:Button}));
// Billing gate's own server/owner behavior remains covered by its existing suite.
mock.module('@/components/NativeBillingGate',()=>({NativeBillingGate:(p:any)=><Host>{p.children}</Host>}));
let user:any=null;let access=false;let params:any={};const routes:any[]=[];
const router={push:(r:any)=>routes.push(r),replace:(r:any)=>routes.push(r)};
let redirected:any=null;
mock.module('expo-router',()=>({useRouter:()=>router,useLocalSearchParams:()=>params,Redirect:(p:any)=>{redirected=p.href;return <Host/>;}}));
mock.module('@/providers/auth',()=>({useAuth:()=>({user})}));
mock.module('@/lib/nativeBillingRuntime',()=>({normalBillingEnabled:true}));
mock.module('@/lib/purchaseFirstPolicy',()=>({purchaseFirstEnabled:false,usePurchaseFirstPolicy:()=>({data:false,refetch:async()=>{}})}));
const product={identifier:'byis_pro_monthly_5',priceString:'$11.99',subscriptionPeriod:'P1M',introPrice:{price:0,period:'P1W',cycles:1}};
let outcome='pending';let buys=0;let restores=0;let permissionCalls=0;
const offerings={current:{monthly:{product}}};
mock.module('@/lib/purchases',()=>({usePreAccountPurchase:()=>({mutateAsync:async()=>({status:'pending'})}),useClaimPreAccountPurchase:()=>({mutateAsync:async()=>false}),hasPro:()=>false,trialEligibility:async()=>2,useIsPro:()=>access,useCustomerInfo:()=>({data:null,refetch:async()=>{}}),useNativeServerAccess:()=>({refetch:async()=>{}}),useOfferings:()=>({data:offerings,isLoading:false,isError:false}),usePurchasePackage:()=>({mutateAsync:async()=>{buys++;await Promise.resolve();return {status:outcome};}}),useRestorePurchases:()=>({mutateAsync:async()=>{restores++;return false;}})}));
mock.module('@/lib/trialReminder',()=>({enableTrialReminder:async()=>{permissionCalls++;return 'enabled';},syncTrialReminder:async()=> 'scheduled'}));
const {readAnswerFirst,writeAnswerFirst,claimAnswerFirst}=await import('../lib/answerFirstStorage');
const answer={diff:'clarity',ctx:'work',rec:'bury'};
await writeAnswerFirst({...answer,strokes:['not persisted']} as any);
assert.ok(![...data.values()].join('').includes('strokes'));
failedKey='bysi.owner.v1:owner-a:cc.answerFirst.v1';
await assert.rejects(claimAnswerFirst('owner-a'));
await assert.rejects(claimAnswerFirst('owner-b'));
failedKey='';await claimAnswerFirst('owner-a');
assert.deepEqual(await claimAnswerFirst('owner-a'),answer,'repeated return must not erase preferences');
assert.deepEqual(await readAnswerFirst('owner-b'),{});
await writeAnswerFirst(answer);
const {default:Route}=await import('../app/answer-onboarding');
let root:any;await act(async()=>{root=create(<Route/>);});
assert.equal(ui.offer.trial,true);assert.equal(ui.offer.renewal,'$11.99 monthly');assert.equal(ui.access,false);
await act(async()=>ui.onAccount('signup',answer));assert.deepEqual(routes.pop(),{pathname:'/continue-from-web',params:{mode:'signup',returnTo:'answer-first'}});
await act(async()=>ui.onPractice(answer));assert.equal(routes.length,0);assert.equal(buys,0);assert.equal(permissionCalls,0);
await act(async()=>root.unmount());user={id:'owner-a'};params={source:'account-return'};
await act(async()=>{root=create(<Route/>);});assert.deepEqual(ui.initialAnswers,answer);assert.equal(ui.initialScreen,'offer');
await act(async()=>ui.onBuy());assert.equal(buys,0,'purchase waits for explicit confirmation');
const confirm=root.root.findAllByType('button').find((b:any)=>b.props.label==='Confirm free trial with Apple');assert.ok(confirm);
await act(async()=>{confirm.props.onPress();confirm.props.onPress();});assert.equal(buys,1);assert.equal(ui.initialScreen,'confirm');assert.equal(ui.confirmation,'pending');assert.equal(ui.access,false);assert.equal(permissionCalls,0);
await act(async()=>{ui.onRestore();ui.onRestore();});assert.equal(restores,1);
access=true;await act(async()=>root.update(<Route/>));await act(async()=>{ui.onPractice(answer);ui.onPractice(answer);});assert.equal(routes.pop(),'/first-practice');assert.equal(routes.length,0,'duplicate handoff cannot mount two recording surfaces');
await act(async()=>root.unmount());
const {default:FirstPractice}=await import('../app/first-practice');
access=false;await act(async()=>{root=create(<FirstPractice/>);});assert.equal(redirected,null,'unverified access must not enter lesson');
access=true;await act(async()=>root.update(<FirstPractice/>));
assert.deepEqual(redirected,{pathname:'/approved-lesson/[lessonId]',params:{lessonId:'m1-l1'}},'first paid experience is Module 1 Lesson 1, not a standalone scenario');
await act(async()=>root.unmount());
console.log('PASS answer-first adapter: actual owner storage, partial-write isolation, repeated return, email route, monthly offer, explicit confirmation, duplicate purchase/restore, and access-only practice. SDK/Auth/server gate mocked.');
