import { mock } from 'bun:test';
import { plugin } from 'bun';
import assert from 'node:assert/strict';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
plugin({name:'buyer-assets',setup(b){b.onLoad({filter:/\.(png|ttf)$/},()=>({contents:'export default 1',loader:'js'}));}});
const Host=({children}:any)=>React.createElement('div',null,children);
const buttons:any[]=[];
const Button=(p:any)=>{buttons.push(p);return React.createElement(Host,null,p.label??p.children);};
mock.module('react-native',()=>({View:Host,Text:Host,ScrollView:Host,TextInput:Host,Pressable:Button,KeyboardAvoidingView:Host,ActivityIndicator:Host,Keyboard:{dismiss(){}},Platform:{OS:'web',select:(x:any)=>x.web??x.default},StyleSheet:{create:(x:any)=>x},AccessibilityInfo:{announceForAccessibility(){}}}));
mock.module('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:0,bottom:0})}));
mock.module('lucide-react-native',()=>Object.fromEntries(['ArrowUp','Check','Mic','RotateCcw','Square','X'].map(x=>[x,()=>null])));
mock.module('@/components/ui',()=>({Backdrop:()=>null,Eyebrow:Host,Meter:Host,PressCard:Button,PrimaryButton:Button,GhostButton:Button,tap(){}}));
mock.module('@/components/PaidProductUI',()=>({ProductCard:Host,SectionLabel:Host}));
let options:any;
let micStarts=0;
mock.module('@/lib/useDictation',()=>({useDictation:(o:any)=>{options=o;return {status:'idle',start:async()=>{micStarts++;},cancel:async()=>{},stop:async()=>null};}}));
let params:any={lessonId:'m1-l1'};
mock.module('expo-router',()=>({useRouter:()=>({replace(){},back(){}}),useLocalSearchParams:()=>params}));
mock.module('@/providers/store',()=>({useStore:()=>({access:{entitlement:'pro'},convertedLessonProgress:[{lessonId:'m1-l1'}],logDrill(){},markChallengeDayDone(){}})}));
(globalThis as any).__DEV__=true;
const {default:QuickRep}=await import('../app/quick-rep/[lessonId]');
renderToStaticMarkup(React.createElement(QuickRep));
assert.deepEqual(options,{paidPractice:true},'actual Quick Rep screen must select protected dictation');
const mic=buttons.find(x=>x.accessibilityLabel==='Record Quick Rep');
assert.ok(mic,'actual consumer microphone control must render');
await mic.onPress();assert.equal(micStarts,1);
const {DRILLS}=await import('@/constants/drills');params={id:DRILLS[0]!.id};options=undefined;
const {default:Drill}=await import('../app/drill/[id]');renderToStaticMarkup(React.createElement(Drill));
assert.deepEqual(options,{paidPractice:true},'actual drill screen must select protected dictation');
console.log('Mounted Quick Rep and drill select protected voice; synthetic native hosts and recorder only.');
