import {mock} from 'bun:test';
import assert from 'node:assert/strict';
import React from 'react';
const {verifyComponentTestDeps}=await import('../scripts/component-test-deps');
const {create,act}=await import(verifyComponentTestDeps());
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;(globalThis as any).__DEV__=true;
const disk=new Map<string,string>([['cc.profile.v1',JSON.stringify({focus:'work',pattern:'freeze',win:'yes',persona:'woman-hope',reaction:'defensive',createdAt:1})]]);
const raw={getItem:async(k:string)=>disk.get(k)??null,setItem:async(k:string,v:string)=>{disk.set(k,v);},removeItem:async(k:string)=>{disk.delete(k);},getAllKeys:async()=>[...disk.keys()],multiRemove:async(ks:string[])=>{ks.forEach(k=>disk.delete(k));}};
mock.module('@react-native-async-storage/async-storage',()=>({default:raw}));
const listeners=new Set<any>();const userA={id:'A',email:'a@invalid',is_anonymous:false,email_confirmed_at:'2026-09-01'};
let session:any={user:userA,access_token:'fixture-A'};
const auth={getSession:async()=>({data:{session},error:null}),getUser:async()=>({data:{user:session?.user??null},error:null}),onAuthStateChange:(cb:any)=>{listeners.add(cb);return {data:{subscription:{unsubscribe(){listeners.delete(cb);}}}};},signOut:async()=>{session=null;for(const cb of listeners)cb('SIGNED_OUT',null);return {error:null};}};
mock.module('@/lib/supabase',()=>({supabase:{auth},authEnvironment:{url:'https://pqqxaklcburdxjfeolmd.supabase.co',key:'sb_publishable_fixture',staging:true},isAuthConfigured:true}));
mock.module('@/lib/purchases',()=>({identifyPurchasesUser:async()=>null,clearPurchasesIdentity:async()=>{},useIsPro:()=>false,hasPro:()=>{throw Error('Unexpected Apple entitlement read');}}));
mock.module('@/lib/reminders',()=>({cancelChallengeNudge:async()=>{},cancelDailyReminder:async()=>{},syncChallengeNudge:async()=>{}}));
mock.module('@/lib/baselineAudio',()=>({deleteAllBaselineAudioStrict:async()=>{},deleteBaselineAudioStrict:async()=>{}}));

const privateResult={schema_version:1,kind:'bysi_private_web_result',provenance:{generation_id:'fixture-generation',rehearsal_id:'fixture-rehearsal',provider_request_id:'fixture-request',model:'fixture-model',generated_at:'2026-09-06T12:00:00.000Z',producer_version:'fixture-v1',source:'server_generation'},result:{mode:'result',outputVersion:'bysi-free-rehearsal-result-v1-2026-08-12',pressure_moment:{headline:'Exact fixture headline',conclusion:'Stored conclusion',how_bysi_read_this:{observed:'Stored observation',why_it_matters:'Stored reason',confidence:'Limited evidence'}},practice_shift:{headline:'Stored shift',current_pattern:['First','Second','Third'],practice_target:['Target one','Target two','Target three'],goal_line:'Stored goal',honesty_note:'Not a measured gain'},starting_index:{overall:null,label:'Starting Index',coverage_note:'Partial coverage',score_note:'Stored caveat',focus_dimension:'Repair',observed_dimensions:[{name:'Clarity',score:43.25,evidence:'Exact evidence'}],unobserved_dimensions:['Specificity','Listening','Steadiness','Boundaries','Repair']},recommended_path:{first_module:'Get to the Point',reason:'Exact recommendation',next_modules:['Repair What Went Wrong']}}};
import {plugin} from 'bun';
plugin({name:'buyer-journey-assets',setup(b){b.onLoad({filter:/\.(png|ttf)$/},()=>({contents:'export default 1',loader:'js'}));}});
const Host=(p:any)=>React.createElement('view',p,p.children);
const Button=(p:any)=>React.createElement('button',p,p.label??p.children);
const appEvents=new Set<any>();
mock.module('react-native',()=>({View:Host,Text:Host,ScrollView:Host,TextInput:(p:any)=>React.createElement('input',p),Pressable:Button,KeyboardAvoidingView:Host,ActivityIndicator:Host,AppState:{addEventListener:(_:any,cb:any)=>{appEvents.add(cb);return {remove(){appEvents.delete(cb);}};}},Platform:{OS:'web',select:(v:any)=>v.web??v.default},StyleSheet:{create:(v:any)=>v,hairlineWidth:1},Alert:{alert(){}},Animated:{},Easing:{},Linking:{},AccessibilityInfo:{announceForAccessibility(){}}}));
mock.module('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:0,bottom:0})}));
mock.module('lucide-react-native',()=>Object.fromEntries(['Bookmark','ShieldCheck','AlertCircle','Check','ChevronDown','Clock3','RefreshCw','Sparkles','Star','TrendingUp','Mic','Square','X'].map(x=>[x,()=>null])));
mock.module('@/components/ui',()=>({Backdrop:()=>null,Eyebrow:Host,GlassCard:Host,PressCard:Button,PrimaryButton:Button,GhostButton:Button,Reveal:Host,StateDock:Host,Thinking:Host,MicControl:Button,tap(){},useReducedMotion:()=>true}));
mock.module('@/components/PaidProductUI',()=>({ProductCard:Host,SectionLabel:Host,StatusPill:Host}));
mock.module('react-native-webview',()=>({WebView:(p:any)=>React.createElement('webview',p)}));
mock.module('expo-file-system',()=>({File:class {exists=false;delete(){}}}));
mock.module('expo-crypto',()=>({randomUUID:()=>crypto.randomUUID()}));
// Native deck asset and voice hosts are explicit substitutes, not device proof.
mock.module('@/lib/approvedDeckLoader',()=>({loadApprovedDeckHtml:async()=>'<html>canonical asset host substitute</html>',loadConvertedHandoffDeckHtml:async()=>'<html>canonical asset host substitute</html>',loadModuleCloseDeckHtml:async()=>'<html>canonical asset host substitute</html>'}));
mock.module('@/lib/lessonFeedbackService',()=>({submitLessonFeedback:async()=>{throw Error('No external feedback');}}));
const cancel=async()=>{};
mock.module('@/lib/useDictation',()=>({useDictation:()=>({status:'idle',cancel,start:async()=>{},stop:async()=>null})}));
mock.module('@/lib/voice',()=>({deleteGeneratedVoiceCacheStrict:async()=>{},useSpeech:()=>({status:'idle'}),resetSpeech:cancel,replaySpeech:cancel,unlockAudioPlayback:cancel,preparePaidPilotAudio:async()=>{throw Error('Fixture has no audio');},playPreparedPilotAudio:cancel,speakPaidPilotAudio:cancel,speakPaidPilotAudioToCompletion:cancel}));
let generationCalls=0;
mock.module('@/lib/ai',()=>({generateM1L1DynamicReply:async()=>{generationCalls++;throw Error('Protected server denied');},generateApprovedRehearsalDynamicReply:async()=>{throw Error('not used');},generateDebrief:async()=>{throw Error('not used');},nextCounterpartTurn:async()=>{throw Error('not used');}}));
let appleReads=0;
mock.module('@/lib/purchases',()=>({identifyPurchasesUser:async()=>null,clearPurchasesIdentity:async()=>{},useIsPro:()=>false,hasPro:()=>{throw Error('Unexpected Apple entitlement read');},useCustomerInfo:()=>{appleReads++;throw Error('Unexpected Apple ask');},useOfferings:()=>{appleReads++;throw Error('Unexpected Apple ask');},usePurchasePackage:()=>{throw Error('Unexpected purchase');},useRestorePurchases:()=>{throw Error('Unexpected restore');}}));
const sessionId='12345678-1234-4234-8234-123456789abc';
let paid=true;let rpcWait:Promise<Response>|null=null;const calls:any[]=[];
globalThis.fetch=async(url:any,init:any)=>{
 calls.push({url:String(url),authorization:init.headers.Authorization,body:JSON.parse(init.body)});
 if(String(url).endsWith('/discover'))return Response.json({items:session?.user.id==='A'?[{sessionId,capturedAt:'2026-09-06T12:00:00Z',expiresAt:'2099-01-01T00:00:00Z'}]:[],nextCursor:null});
 if(String(url).endsWith('/restore'))return Response.json({sessionId,privateResult,livemode:false,source:'stripe',access:true,status:'trialing',expiresAt:'2099-01-01T00:00:00Z',reconciliationRequired:false,cancelAtPeriodEnd:false});
 if(String(url).endsWith('/bysi_staging_paid_access'))return rpcWait??Response.json(paid);
 throw Error('Unexpected network URL '+url);
};
let navigate:any,params:any={};let location:any='/staging-web-result';
const router={replace:(r:any)=>navigate(r),push:(r:any)=>navigate(r),canGoBack:()=>false,back:()=>navigate('/staging-web-result')};
mock.module('expo-router',()=>({useRouter:()=>router,useLocalSearchParams:()=>params}));
const {QueryClient,QueryClientProvider}=await import('@tanstack/react-query');
const {AuthProvider,useAuth}=await import('../providers/auth');
const {StoreProvider,useStore}=await import('../providers/store');
const {default:Result}=await import('../app/staging-web-result');
const {default:Lesson}=await import('../app/approved-lesson/[lessonId]');
const {default:Rehearsal}=await import('../app/approved-rehearsal/[lessonId]');
const {default:Paywall}=await import('../app/paywall');
let account:any,store:any;
function RouterHost(){account=useAuth();store=useStore();const [route,setRoute]=React.useState<any>('/staging-web-result');navigate=(r:any)=>{location=r;setRoute(r);};params=typeof route==='string'?{}:route.params;const path=typeof route==='string'?route:route.pathname;return React.createElement(path.startsWith('/approved-lesson')?Lesson:path.startsWith('/approved-rehearsal')?Rehearsal:path==='/paywall'?Paywall:Result);}
const client=new QueryClient({defaultOptions:{queries:{retry:false}}});
const app=()=>React.createElement(QueryClientProvider,{client},React.createElement(AuthProvider,null,React.createElement(StoreProvider,null,React.createElement(RouterHost))));
let root:any;await act(async()=>{root=create(app());});
const flush=()=>act(async()=>{await new Promise(r=>setTimeout(r,5));});await flush();
const text=()=>JSON.stringify(root.toJSON());
const button=(label:string)=>root.root.findAllByType('button').find((x:any)=>x.props.label===label);
assert.ok(text().includes('Exact fixture headline'));assert.ok(text().includes('43.25'));assert.ok(text().includes('Not scored'));
assert.equal(store.scoredPracticeHistory.length,0);assert.equal(store.activeScenarioRun,null);
assert.ok(button('Continue to next practice'));assert.equal(button('Continue to next practice').props.disabled,false);
await act(async()=>{button('Continue to next practice').props.onPress();});await flush();
assert.deepEqual(location,{pathname:'/approved-lesson/[lessonId]',params:{lessonId:'m1-l1'}});
assert.equal(root.root.findAllByType('webview').length,1,'actual approved lesson is admitted without RevenueCat/development Pro');
assert.equal(store.scoredPracticeHistory.length,0);assert.equal(store.activeScenarioRun,null);
await act(async()=>{root.root.findByType('webview').props.onMessage({nativeEvent:{data:JSON.stringify({type:'start-rehearsal'})}});});await flush();
assert.equal(location.pathname,'/approved-rehearsal/[lessonId]');
assert.ok(store.activeScenarioRun?.run.id,'actual rehearsal route creates owner-scoped canonical run');
assert.equal(store.activeScenarioRun.run.practiceId,(await import('../lib/convertedLesson')).M1_L1_CONVERSION.practiceId);
assert.ok(root.root.findAllByType('input').length>0,'actual M1L1 learner runtime is mounted, not a sentinel');
assert.equal(store.scoredPracticeHistory.length,0);assert.equal(store.convertedLessonProgress.length,0);assert.equal(appleReads,0);
const ownerRunId=store.activeScenarioRun.run.id;
(globalThis as any).requestAnimationFrame=(cb:any)=>{cb(0);return 1;};
await act(async()=>{root.root.findByType('input').props.onChangeText('Synthetic learner opener, not generated or measured.');});
await act(async()=>{button('Review typed transcript').props.onPress();});await flush();
assert.ok(text().includes('Approve this exact transcript.'));
assert.ok(text().includes('Synthetic learner opener, not generated or measured.'));
assert.equal(store.activeScenarioRun.run.state,'confirm_attempt_transcript');
assert.equal(store.scoredPracticeHistory.length,0);
// Advance the clock beyond the real admission lease without inventing a new decision.
const realNow=Date.now;const expiredAt=realNow()+31000;Date.now=()=>expiredAt;
await act(async()=>{root.update(app());});
assert.ok(text().includes("Practice access is not currently verified"));
assert.equal(root.root.findAllByType("input").length,0);Date.now=realNow;
// Current server denial after expiry removes the learner runtime, not another Apple ask.
paid=false;await act(async()=>{account.stagingPracticeAccess.invalidate();});await flush();
assert.ok(text().includes('Practice access is not currently verified'));assert.equal(root.root.findAllByType('input').length,0);assert.equal(appleReads,0);
await act(async()=>{navigate('/paywall');});assert.ok(text().includes('Your web subscription is already verified'));assert.equal(appleReads,0);
await act(async()=>{navigate('/staging-web-result');});
await act(async()=>{button('Continue to next practice').props.onPress();});await flush();
assert.equal(location,'/staging-web-result');assert.ok(text().includes('Practice access is not currently verified'));
// A pending genuine admission transport response cannot navigate after logout/switch.
let release!:(v:Response)=>void;rpcWait=new Promise(r=>{release=r;});
await act(async()=>{button('Continue to next practice').props.onPress();});
await act(async()=>{await button('Sign out').props.onPress();});
release(Response.json(true));await flush();assert.equal(location,'/staging-web-result');assert.equal(store.activeScenarioRun,null);assert.ok(!text().includes('Exact fixture headline'));
await act(async()=>{session={user:{...userA,id:'B'},access_token:'fixture-B'};for(const cb of listeners)cb('SIGNED_IN',session);});await flush();
assert.equal(store.activeScenarioRun,null);assert.equal(store.scoredPracticeHistory.length,0);assert.ok(!text().includes(ownerRunId));
assert.ok(calls.filter(x=>x.url.endsWith('/bysi_staging_paid_access')).every(x=>x.authorization==='Bearer fixture-A'&&Object.keys(x.body).length===0));
assert.equal(generationCalls,0,'opening practice does not invent a model response or completed history');
await act(async()=>root.unmount());
// Real providers reconstructed against the same synthetic disk: only A resumes A.
session={user:userA,access_token:'fixture-A-restarted'};rpcWait=null;paid=true;
await act(async()=>{root=create(app());});await flush();
assert.equal(store.activeScenarioRun.run.id,ownerRunId);
assert.equal(store.scoredPracticeHistory.length,0);assert.equal(store.convertedLessonProgress.length,0);
await act(async()=>{button('Continue to next practice').props.onPress();});await flush();
await act(async()=>{root.root.findByType('webview').props.onMessage({nativeEvent:{data:JSON.stringify({type:'start-rehearsal'})}});});await flush();
assert.equal(store.activeScenarioRun.run.id,ownerRunId,'cold start resumes canonical run rather than fabricating another');
assert.ok(root.root.findAllByType('input').length>0);assert.equal(appleReads,0);
await act(async()=>root.unmount());client.clear();
console.log('PASS actual result → approved lesson → M1L1 learner runtime; current RPC denial, pending-response logout, owner switch, no second Apple ask. Synthetic Auth/HTTP/storage/native hosts; no provider/device/payment proof.');
