import {mock} from 'bun:test';
import {plugin} from 'bun';
plugin({name:'login-host-assets',setup(b){b.onLoad({filter:/\.(png|ttf)$/},()=>({contents:'export default 1',loader:'js'}));}});
import assert from 'node:assert/strict';
import React from 'react';
const {verifyComponentTestDeps}=await import('../scripts/component-test-deps');
const {create,act}=await import(verifyComponentTestDeps());
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;(globalThis as any).__DEV__=true;
const disk=new Map<string,string>([['cc.profile.v1',JSON.stringify({focus:'work',pattern:'freeze',win:'yes',persona:'woman-hope',reaction:'defensive',createdAt:1})]]);
const raw={getItem:async(k:string)=>disk.get(k)??null,setItem:async(k:string,v:string)=>{disk.set(k,v);},removeItem:async(k:string)=>{disk.delete(k);},getAllKeys:async()=>[...disk.keys()],multiRemove:async(ks:string[])=>{ks.forEach(k=>disk.delete(k));}};
mock.module('@react-native-async-storage/async-storage',()=>({default:raw}));
const listeners=new Set<any>();const userA={id:'A',email:'a@invalid',is_anonymous:false,email_confirmed_at:'2026-09-01'};
let session:any=null;let rejectReadback=true;let readbacks=0;
const auth={getSession:async()=>({data:{session},error:null}),getUser:async()=>{readbacks++;
 if(rejectReadback && process.env.BYSI_LOGIN_DENIAL==='expired')return {data:{user:null},error:new Error('synthetic expired access')};
 if(rejectReadback && process.env.BYSI_LOGIN_DENIAL==='switch'){const original=session.user;session={user:{id:'B',email:'b@invalid',is_anonymous:false},access_token:'fixture-B'};for(const cb of listeners)cb('SIGNED_IN',session);return {data:{user:original},error:null};}
 return {data:{user:rejectReadback?{...userA,id:'wrong-owner'}:session?.user??null},error:null};},onAuthStateChange:(cb:any)=>{listeners.add(cb);return {data:{subscription:{unsubscribe(){listeners.delete(cb);}}}};},signOut:async()=>{session=null;for(const cb of listeners)cb('SIGNED_OUT',null);return {error:null};}};
mock.module('@/lib/supabase',()=>({supabase:{auth},authEnvironment:{url:'https://production.invalid',staging:false},isAuthConfigured:true}));
mock.module('@/lib/purchases',()=>({trialEligibility: async () => 0, identifyPurchasesUser:async()=>null,clearPurchasesIdentity:async()=>{},useIsPro:()=>false}));
mock.module('@/lib/reminders',()=>({cancelChallengeNudge:async()=>{},cancelDailyReminder:async()=>{},syncChallengeNudge:async()=>{}}));
mock.module('@/lib/baselineAudio',()=>({deleteAllBaselineAudioStrict:async()=>{},deleteBaselineAudioStrict:async()=>{}}));
mock.module('@/lib/voice',()=>({deleteGeneratedVoiceCacheStrict:async()=>{}}));

(auth as any).signInWithPassword=async()=>{session={user:userA,access_token:'fixture-A'};for(const cb of listeners)cb('SIGNED_IN',session);return {data:{session},error:null};};
const Host=(p:any)=>React.createElement('host',p,p.children);
mock.module('react-native',()=>({View:Host,Text:Host,ScrollView:Host,TextInput:(p:any)=>React.createElement('input',p),ActivityIndicator:Host,KeyboardAvoidingView:Host,Platform:{OS:'web',select:(v:any)=>v.web??v.default},StyleSheet:{create:(v:any)=>v}}));
mock.module('lucide-react-native',()=>({ArrowLeft:()=>null,LockKeyhole:()=>null}));
mock.module('react-native-svg',()=>({default:Host,Circle:Host,Path:Host,Rect:Host}));
mock.module('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:0,bottom:0})}));
mock.module('@/components/ui',()=>({Backdrop:()=>null,Eyebrow:Host,Reveal:Host,PressCard:Host,GhostButton:(p:any)=>React.createElement('button',p,p.label),PrimaryButton:(p:any)=>React.createElement('button',p,p.label)}));
let route:any;
mock.module('expo-router',()=>({useLocalSearchParams:()=>({}),useRouter:()=>({replace:(r:any)=>{route=r;},push(){},back(){}})}));
const {QueryClient,QueryClientProvider}=await import('@tanstack/react-query');
const {AuthProvider,useAuth}=await import('../providers/auth');
const {StoreProvider,useStore}=await import('../providers/store');
const {default:Login}=await import('../app/continue-from-web');
const {LegacyEntryScreen:Entry}=await import('../app/entry');
let Screen=Login;
let account:any,store:any;
const Probe=()=>{account=useAuth();store=useStore();return React.createElement(Screen);};
const client=new QueryClient();let root:any;
await act(async()=>{root=create(React.createElement(QueryClientProvider,{client},React.createElement(AuthProvider,null,React.createElement(StoreProvider,null,React.createElement(Probe)))));});
await act(async()=>{root.root.findAllByType('input')[0].props.onChangeText('a@invalid');root.root.findAllByType('input')[1].props.onChangeText('synthetic-password');});
await act(async()=>{root.root.findAllByType('button').find((b:any)=>b.props.label==='Log in').props.onPress();});
assert.equal(route,undefined,'mismatched verified owner must not navigate');
assert.ok(readbacks>0,'login verifies the provider user rather than trusting a session envelope');
assert.equal(account.user,null);
rejectReadback=false;
await act(async()=>{session=null;for(const cb of listeners)cb('SIGNED_OUT',null);});
await act(async()=>{root.root.findAllByType('input')[0].props.onChangeText('a@invalid');root.root.findAllByType('input')[1].props.onChangeText('synthetic-password');});
await act(async()=>{root.root.findAllByType('button').find((b:any)=>b.props.label==='Log in').props.onPress();});
assert.equal(account.user.id,'A');
assert.equal(route,'/(tabs)','normal login must not invoke a stale guest-store callback after the owner changes');
assert.equal(store.activePracticeSession,null);assert.equal(store.profile,null);
assert.ok(disk.has('cc.profile.v1'));
Screen=Entry;await act(async()=>{root.update(React.createElement(QueryClientProvider,{client},React.createElement(AuthProvider,null,React.createElement(StoreProvider,null,React.createElement(Probe)))));});
auth.signOut=async()=>({error:new Error('synthetic offline') as any});
await act(async()=>{await root.root.findAllByType('button').find((b:any)=>b.props.label==='Sign out').props.onPress();});
assert.ok(JSON.stringify(root.toJSON()).includes('Sign out could not be confirmed'),'entry retains a visible logout retry after its account subtree remounts');
await act(async()=>root.unmount());client.clear();
console.log('PASS actual normal login navigation with owner quarantine, no stale guest reassignment. Synthetic Auth/native/storage hosts.');
