import {mock} from 'bun:test';
import assert from 'node:assert/strict';
import React from 'react';
const {verifyComponentTestDeps}=await import('../scripts/component-test-deps');
const {create,act}=await import(verifyComponentTestDeps());
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;(globalThis as any).__DEV__=true;
const disk=new Map<string,string>([['cc.profile.v1',JSON.stringify({focus:'work',pattern:'freeze',win:'yes',persona:'woman-hope',reaction:'defensive',createdAt:1})]]);
const raw={getItem:async(k:string)=>disk.get(k)??null,setItem:async(k:string,v:string)=>{disk.set(k,v);},removeItem:async(k:string)=>{disk.delete(k);},getAllKeys:async()=>[...disk.keys()],multiRemove:async(ks:string[])=>{ks.forEach(k=>disk.delete(k));}};
mock.module('@react-native-async-storage/async-storage',()=>({default:raw}));
const listeners=new Set<any>();const userA={id:'A',email:'a@invalid',is_anonymous:false,email_confirmed_at:'2026-09-01'};
let session:any={user:userA,access_token:'fixture-A'};
const auth={getSession:async()=>({data:{session},error:null}),getUser:async()=>({data:{user:session?.user??null},error:null}),onAuthStateChange:(cb:any)=>{listeners.add(cb);return {data:{subscription:{unsubscribe(){listeners.delete(cb);}}}};},signOut:async()=>{session=null;for(const cb of listeners)cb('SIGNED_OUT',null);return {error:null};}};
mock.module('@/lib/supabase',()=>({supabase:{auth},authEnvironment:{url:'https://production.invalid',staging:false},isAuthConfigured:true}));
mock.module('@/lib/purchases',()=>({trialEligibility: async () => 0, identifyPurchasesUser:async()=>null,clearPurchasesIdentity:async()=>{},useIsPro:()=>false}));
mock.module('@/lib/reminders',()=>({cancelChallengeNudge:async()=>{},cancelDailyReminder:async()=>{},syncChallengeNudge:async()=>{}}));
mock.module('@/lib/baselineAudio',()=>({deleteAllBaselineAudioStrict:async()=>{},deleteBaselineAudioStrict:async()=>{}}));
mock.module('@/lib/voice',()=>({deleteGeneratedVoiceCacheStrict:async()=>{}}));
const {QueryClient,QueryClientProvider}=await import('@tanstack/react-query');
mock.module('react-native',()=>({View:'view',Text:'text',Platform:{OS:'web'}}));
const {AuthProvider,useAuth}=await import('../providers/auth');
const {StoreProvider,useStore}=await import('../providers/store');
mock.module('@/components/ui',()=>({PrimaryButton:(p:any)=>React.createElement('button',p,p.label)}));
const {AccountLogout}=await import('../components/AccountLogout');
let account:any,store:any;const probe=()=>{account=useAuth();store=useStore();return React.createElement('output',null,store.profile?.focus??'empty',React.createElement(AccountLogout));};
const client=new QueryClient({defaultOptions:{queries:{retry:false}}});
const app=()=>React.createElement(QueryClientProvider,{client},React.createElement(AuthProvider,null,React.createElement(StoreProvider,null,React.createElement(probe))));
let root:any;await act(async()=>{root=create(app());});
assert.equal(store.profile,null,'legacy unowned private profile must be quarantined, not claimed by A');
const aSave=store.saveProfile;await act(async()=>{await store.saveProfile({focus:'work',pattern:'freeze',win:'yes',persona:'woman-hope',reaction:'defensive',createdAt:2});});
assert.equal(store.profile.focus,'work');
await act(async()=>{session={user:{...userA,id:'B'},access_token:'fixture-B'};for(const cb of listeners)cb('SIGNED_IN',session);});
assert.equal(store.profile,null,'owner B must never see A profile');
await assert.rejects(aSave({focus:'family',pattern:'freeze',win:'yes',persona:'woman-hope',reaction:'defensive',createdAt:3}),/Account changed/);
assert.equal(store.profile,null);
await act(async()=>{await root.root.findByType('button').props.onPress();});
assert.equal(account.session,null);assert.equal(store.profile,null);
await act(async()=>{session={user:userA,access_token:'fixture-A2'};for(const cb of listeners)cb('SIGNED_IN',session);});
assert.equal(store.profile.focus,'work','A can restore only its namespace');
await act(async()=>{root.unmount();});
await act(async()=>{root=create(app());});
assert.equal(store.profile.focus,'work','cold start restores exact owner');
await act(async()=>{for(const id of ['B','A']) { session={user:{...userA,id},access_token:'fixture-'+id};for(const cb of listeners)cb('SIGNED_IN',session); }});
await act(async()=>{await store.saveProfile({focus:'family',pattern:'freeze',win:'yes',persona:'woman-hope',reaction:'defensive',createdAt:4});});
assert.equal(store.profile.focus,'family','batched A→B→A must remount with a fresh lease');
const originalGet=auth.getSession;const savedSession=session;let releaseSession!:(v:any)=>void;
auth.getSession=()=>new Promise(r=>{releaseSession=r;});
const staleStart=account.startNativeSession();auth.getSession=originalGet;
await act(async()=>{await account.logout();});
await act(async()=>{releaseSession({data:{session:savedSession},error:null});await staleStart;});
assert.equal(account.session,null,'late session starter must not resurrect A after logout');
await act(async()=>{session=savedSession;for(const cb of listeners)cb('SIGNED_IN',session);});
const normalSignOut=auth.signOut;auth.signOut=async()=>({error:new Error('synthetic offline') as any});
await act(async()=>{await root.root.findByType('button').props.onPress();});
assert.equal(account.session,null);assert.equal(store.profile,null);
assert.ok(JSON.stringify(root.toJSON()).includes('Sign out could not be confirmed'));
auth.signOut=normalSignOut;await act(async()=>{await root.root.findByType('button').props.onPress();});
assert.equal(account.logoutError,'');
await act(async()=>{session=savedSession;for(const cb of listeners)cb('SIGNED_IN',session);});
await act(async()=>{await store.reset();});
assert.equal(account.session,null);assert.equal(store.profile,null);
assert.ok(disk.has('cc.profile.v1'),'legacy bytes preserved in quarantine');
await act(async()=>root.unmount());client.clear();
console.log('PASS actual AuthProvider + StoreProvider: owner switch, stale action, logout, cold start and non-destructive legacy quarantine; synthetic Auth/storage host.');
