import { mock } from 'bun:test';
import { plugin } from 'bun';
import assert from 'node:assert/strict';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { createStagingWebBridge } from '../lib/stagingWebBridge';
plugin({name:'journey-assets',setup(b){b.onLoad({filter:/\.(png|ttf)$/},()=>({contents:'export default 1',loader:'js'}));}});
const Host=({children}:any)=>React.createElement('div',null,children);
const actions:any[]=[];
const Button=(p:any)=>{actions.push(p);return React.createElement(Host,null,p.label??p.children);};
mock.module('react-native',()=>({View:Host,Text:Host,ScrollView:Host,TextInput:Host,ActivityIndicator:Host,Animated:{},Easing:{},Linking:{},AppState:{},Platform:{OS:'web',select:(x:any)=>x.web??x.default},StyleSheet:{create:(x:any)=>x},Alert:{}}));
mock.module('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:0,bottom:0})}));
mock.module('lucide-react-native',()=>Object.fromEntries(['ShieldCheck','AlertCircle','Check','ChevronDown','Clock3','RefreshCw'].map(x=>[x,()=>null])));
mock.module('@/components/ui',()=>({Backdrop:()=>null,Eyebrow:Host,GlassCard:Host,PressCard:Button,PrimaryButton:Button,Reveal:Host,StateDock:Host,tap(){},useReducedMotion:()=>true}));
let route:any;const router={replace:(r:any)=>{route=r;},canGoBack:()=>false};
mock.module('expo-router',()=>({useRouter:()=>router,useLocalSearchParams:()=>({lessonId:'m1-l1'})}));
let appleReads=0;
mock.module('@/lib/purchases',()=>({trialEligibility: async () => 0, useIsPro:()=>false,useCustomerInfo:()=>{appleReads++;throw Error('unexpected Apple offer');},useOfferings:()=>{appleReads++;throw Error('unexpected Apple offer');},usePurchasePackage:()=>{throw Error('unexpected purchase');},useRestorePurchases:()=>{throw Error('unexpected restore');}}));
mock.module('@/components/ScenarioPaidPractice',()=>({ScenarioPaidPractice:()=>{throw Error('must not invent native authority');}}));
let writes=0;
const store={activeScenarioRun:null,convertedLessonProgress:[],moduleCloseProgress:[],devProEnabled:false,archiveActiveScenarioRunStrict:()=>{writes++;},clearActiveScenarioRunStrict:()=>{writes++;},replaceActiveScenarioRunStrict:()=>{writes++;}};
mock.module('@/providers/store',()=>({useStore:()=>store}));
let context:any;mock.module('@/providers/auth',()=>({useAuth:()=>context}));
(globalThis as any).__DEV__=true;
const user={id:'synthetic-owner',is_anonymous:false,email_confirmed_at:'2026-09-06'};
let session:any={access_token:'synthetic-token',user};let listener:any;
const privateResult={schema_version:1,kind:'bysi_private_web_result',provenance:{generation_id:'fixture-generation',rehearsal_id:'fixture-rehearsal',provider_request_id:'fixture-request',model:'fixture-model',generated_at:'2026-09-06T12:00:00.000Z',producer_version:'fixture-v1',source:'server_generation'},result:{mode:'result',outputVersion:'bysi-free-rehearsal-result-v1-2026-08-12',pressure_moment:{headline:'Exact fixture headline',conclusion:'Stored conclusion',how_bysi_read_this:{observed:'Stored observation',why_it_matters:'Stored reason',confidence:'Limited evidence'}},practice_shift:{headline:'Stored shift',current_pattern:['First','Second','Third'],practice_target:['Target one','Target two','Target three'],goal_line:'Stored goal',honesty_note:'Not a measured gain'},starting_index:{overall:null,label:'Starting Index',coverage_note:'Partial coverage',score_note:'Stored caveat',focus_dimension:'Repair',observed_dimensions:[{name:'Clarity',score:43.25,evidence:'Exact evidence'}],unobserved_dimensions:['Specificity','Listening','Steadiness','Boundaries','Repair']},recommended_path:{first_module:'Get to the Point',reason:'Exact recommendation',next_modules:['Repair What Went Wrong']}}};
const sessionId='12345678-1234-4234-8234-123456789abc';
const bridge=createStagingWebBridge({developmentBuild:true,authUrl:'http://localhost:54321',reviewed:{authUrl:'http://localhost:54321',environment:'development',endpoints:{activate:'http://localhost/a',restore:'http://localhost/r'}},auth:{getSession:async()=>({data:{session},error:null}),getUser:async()=>({data:{user:session?.user},error:null}),onAuthStateChange:cb=>{listener=cb;return {data:{subscription:{unsubscribe(){}}}};}},fetch:async()=>Response.json({sessionId,privateResult,livemode:false,source:'stripe',access:true,status:'trialing',expiresAt:'2099-01-01T00:00:00Z',reconciliationRequired:false,cancelAtPeriodEnd:false})});
assert.ok(bridge);listener('SIGNED_IN',session);context={stagingWebBridge:bridge,user};
assert.equal(await bridge.restore(sessionId),true);
assert.deepEqual(bridge.getSnapshot().record?.privateResult,privateResult);
const {default:Result}=await import('../app/staging-web-result');
const {default:Paywall}=await import('../app/paywall');
const {default:Rehearsal}=await import('../app/approved-rehearsal/[lessonId]');
const render=(component:any)=>{actions.length=0;return renderToStaticMarkup(React.createElement(component));};
const result=render(Result);
for(const exact of ['Exact fixture headline','43.25','Not scored','Exact recommendation','Target three'])assert.ok(result.includes(exact),exact);
assert.ok(actions.some(x=>x.label === 'Continue to next practice'),'restored result must offer the canonical next-practice handoff');
assert.ok(render(Paywall).includes('Your web subscription is already verified.'));assert.equal(appleReads,0);
bridge.clear();
assert.equal(bridge.getSnapshot().record,null);
assert.equal(bridge.suppressPurchasePrompt(),false,'retained purchase memory is not current verification');
assert.equal(bridge.hasKnownWebPurchase(),true);
listener('TOKEN_REFRESHED',session);
assert.equal(bridge.hasKnownWebPurchase(),true,'same-owner refresh retains the repurchase warning');
assert.ok(render(Paywall).includes('Check your web purchase first.'),'clearing private result must not offer the same owner another subscription');
assert.equal(appleReads,0);
assert.equal(await bridge.restore(sessionId),true);
const denied=render(Rehearsal);assert.ok(denied.includes('A subscription is required for this rehearsal.'));
assert.equal(writes,0,'restoration and denied route must not fabricate or persist practice');
const back=actions.find(x=>typeof x.onPress==='function');assert.ok(back);back.onPress();assert.equal(route,'/paywall');
assert.ok(render(Paywall).includes('Your web subscription is already verified.'));
session={...session,user:{...user,id:'other-owner'}};listener('SIGNED_IN',session);context.user=session.user;
assert.equal(bridge.getSnapshot().record,null);assert.equal(bridge.hasKnownWebPurchase(),false);assert.ok(!render(Result).includes('Exact fixture headline'));
session=null;listener('SIGNED_OUT',null);context.user=null;assert.ok(render(Result).includes('Log in to the verified account'));
assert.equal(writes,0);bridge.dispose();
console.log('Verified local buyer screen boundary: exact restore, duplicate Apple offer suppressed, paid rehearsal blocked, account switch/logout cleared. No provider, database, device or live billing proof.');
