import {mock} from 'bun:test';
import assert from 'node:assert/strict';
const mode=process.argv[2]??'off';
for(const key of Object.keys(process.env))if(key.startsWith('EXPO_PUBLIC_')||key.startsWith('BYSI_ACCOUNT_DELETION_'))delete process.env[key];
const staging=mode==='mixed-staging';
Object.assign(globalThis,{__DEV__:mode!=='release'});
if(mode!=='off')process.env.EXPO_PUBLIC_NATIVE_ACCOUNT_DELETION='normal-results-local-v1';
if(staging)Object.assign(process.env,{EXPO_PUBLIC_BYSI_BUILD_MODE:'staging-account',EXPO_PUBLIC_STAGING_ACCOUNT_DELETION_ENABLED:'reviewed-task1-20260910'});
mock.module('react-native',()=>({Platform:{OS:'web'}}));
mock.module('@react-native-async-storage/async-storage',()=>({default:{}}));
mock.module('../lib/supabase',()=>({authEnvironment:{url:staging?'https://pqqxaklcburdxjfeolmd.supabase.co':mode==='wrong-auth'?'https://wrong.invalid':'https://spvksnddzyvycfoefrcf.supabase.co',staging,applicationId:'app.bysi.staging.account',projectId:'b25c7aba-ef9d-4f88-b7c5-4da1678fcf44'},supabase:{auth:{}}}));
let calls=0;globalThis.fetch=(async()=>{calls++;throw Error('forbidden');}) as any;
const lifecycle=await import('../lib/accountLifecycleRuntime');
assert.equal(lifecycle.accountDeletionAvailable,false,mode);
assert.equal((await lifecycle.deleteAccountIdentity('owner','password',{kind:'unknown'})).success,false);
assert.equal(calls,0);
const runtime=await import('../../server/server/account-deletion/runtime.mjs');
assert.equal(runtime.createAccountDeletionApiRuntime({env:{}}),null);
assert.equal(runtime.createAccountDeletionRuntime({env:{}}),null);
assert.deepEqual(await runtime.runAccountDeletionWorkerOnce({env:{}}),{enabled:false});
const {POST}=await import('../../server/app/functions/v1/account-delete/route.js');
assert.equal((await POST(new Request('https://beforeyousayit.app/functions/v1/account-delete',{method:'POST'}))).status,503);
console.log('PASS default isolation '+mode);
