import {mock} from 'bun:test';
import assert from 'node:assert/strict';
import React from 'react';
const {verifyComponentTestDeps}=await import('../scripts/component-test-deps');
const {create,act}=await import(verifyComponentTestDeps());
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
const Host=(p:any)=>React.createElement('host',p,p.children);
mock.module('react-native',()=>({Text:Host,View:Host,TextInput:(p:any)=>React.createElement('input',p)}));
mock.module('@/components/ui',()=>({PrimaryButton:(p:any)=>React.createElement('button',p,p.label)}));
mock.module('@/lib/accountLifecycleRuntime',()=>({accountDeletionAvailable:false,deleteAccountIdentity:async()=>({success:false,message:'disabled'}),checkAccountDeletionStatus:async()=>({success:false,message:'disabled'}),cleanupDeletedAccountOwner:async()=>{},getRecovery:()=>({request:async()=>({success:true,message:'Recovery requested'})})}));
const {AccountDeletionControls}=await import('../components/AccountLifecycleControls');
let root:any,cancelled=0,submitted=0,checks=0;
const props:any={available:true,ownerId:'A',ownerEmail:'a@example.invalid',billing:{kind:'apple',will_renew:false,expiration_date:'2026-10-01'},clearLocal:async()=>{},onCancel:()=>cancelled++,deleteIdentity:async()=>{submitted++;return {success:false,status:'uncertain',message:'Uncertain'};},checkStatus:async()=>{checks++;return {success:true,status:'accepted',message:'Deletion requested'};}};
await act(async()=>{root=create(React.createElement(AccountDeletionControls,props));});
const text=()=>JSON.stringify(root.toJSON());const button=(label:string)=>root.root.findAllByType('button').find((b:any)=>b.props.label===label);
assert.match(text(),/won.t renew/);assert.doesNotMatch(text(),/will keep renewing/);
assert.ok(button('Forgot password?'));assert.ok(button('Cancel'));
await act(async()=>button('Cancel').props.onPress());assert.equal(cancelled,1);assert.equal(submitted,0);
await act(async()=>root.root.findAllByType('input')[0].props.onChangeText('password'));
await act(async()=>button('Delete account').props.onPress());
assert.equal(submitted,1);assert.equal(checks,1,'uncertain dispatch automatically reads same receipt');
assert.ok(button('Check deletion status'));assert.ok(!button('Delete account'),'accepted request cannot submit another destructive operation');
await act(async()=>root.unmount());
await act(async()=>{root=create(React.createElement(AccountDeletionControls,{...props,deleteIdentity:async()=>({success:true,status:'complete',message:'Your account has been deleted.'}),clearLocal:async()=>{throw Error('disk');}}));});
await act(async()=>root.root.findAllByType('input')[0].props.onChangeText('password'));
await act(async()=>button('Delete account').props.onPress());assert.ok(button('Clear remaining device data'));
await act(async()=>root.unmount());
let seenSignal:AbortSignal|undefined,finish:any;
await act(async()=>{root=create(React.createElement(AccountDeletionControls,{...props,deleteIdentity:async(_owner:string,_password:string,_billing:any,signal:AbortSignal)=>{seenSignal=signal;return new Promise(r=>finish=r);}}));});
await act(async()=>root.root.findAllByType('input')[0].props.onChangeText('password'));
await act(async()=>{void button('Delete account').props.onPress();});
await act(async()=>root.unmount());assert.equal(seenSignal?.aborted,true,'leaving stops preaccept work');finish({success:false,message:'cancelled'});
console.log('PASS deletion recovery UX');
