import {mock} from 'bun:test';
import assert from 'node:assert/strict';
import {harness} from './freeAcquisitionHarness.fixture';
import {FREE_STAGING_ENDPOINT} from '../lib/freeAcquisition';
import {APPROVED_ONBOARDING_SCENARIOS,scenarioFromApproved} from '../constants/onboardingScenarios';
import type {Turn} from '../types/convo';
const h=harness();
process.env.EXPO_PUBLIC_BYSI_BUILD_MODE='staging-account';
process.env.EXPO_PUBLIC_STAGING_FREE_GENERATE_ENDPOINT=FREE_STAGING_ENDPOINT;
delete process.env.EXPO_PUBLIC_GENERATE_ENDPOINT;
(globalThis as any).__DEV__=true;
mock.module('../lib/supabase',()=>({supabase:{auth:h.auth},authEnvironment:{staging:true,url:h.options.authUrl}}));
mock.module('expo-secure-store',()=>({AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY:1,getItemAsync:h.options.storage.getItem,setItemAsync:h.options.storage.setItem}));
globalThis.fetch=h.options.fetch as typeof fetch;
const {nextCounterpartTurn,generateDebrief}=await import('../lib/ai');
const scenario=scenarioFromApproved(APPROVED_ONBOARDING_SCENARIOS[0]!,'woman-hope');
const turns:Turn[]=[{id:'one',role:'user',text:'Can we choose one task?'}];
const one=await nextCounterpartTurn(scenario,'steady',turns,'defensive',scenario.goal);
turns.push({id:'pushback',role:'them',text:one.reply},{id:'two',role:'user',text:'Which one comes first?'});
const two=await nextCounterpartTurn(scenario,'steady',turns,'defensive',scenario.goal);
turns.push({id:'close',role:'them',text:two.reply});
const result=await generateDebrief(scenario,'steady',turns,'defensive',scenario.goal);
assert.deepEqual(result.analysis,h.outputs[2]);
assert.equal(result.analysis.starting_index?.overall,61.25);
assert.equal(h.outputs.length,3);
assert(h.requests.every(r=>new URL(r.url).pathname.startsWith('/api/web-signup/')));
// Existing paid helper remains denied, never borrows the free capability.
await assert.rejects(()=>nextCounterpartTurn(scenario,'steady',turns,'defensive',scenario.goal,undefined,'real_conversation',true));
assert.equal(h.outputs.length,3);
console.log('PASS synthetic native approved opening → pushback → approved reply → close → debrief; paid fallback denied');
