import {mock} from 'bun:test';
import assert from 'node:assert/strict';
import React from 'react';
import {verifyComponentTestDeps} from '../scripts/component-test-deps';
const {create,act}=await import(verifyComponentTestDeps());
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
const Host=(p:any)=>React.createElement('host',p,p.children);
let route='rehearse',redirects:any[]=[];
const router={replace:(r:any)=>{redirects.push(r);}};
let auth:any={isAuthLoading:false,user:null,session:{user:{is_anonymous:true}},isGuestVisit:true};
let store:any={hydrated:true,profile:null,activePracticeSession:null,nativeJourneyStarted:false};
mock.module('expo-router',()=>({Stack:Object.assign(Host,{Screen:()=>null}),useRouter:()=>router,useSegments:()=>[route],useGlobalSearchParams:()=>({})}));
mock.module('@/providers/auth',()=>({AuthProvider:Host,useAuth:()=>auth}));
mock.module('@/providers/store',()=>({StoreProvider:Host,useStore:()=>store}));
mock.module('@/lib/purchases',()=>({trialEligibility: async () => 0,useNativeServerAccess:()=>({})}));
mock.module('@/lib/nativeBillingRuntime',()=>({normalBillingEnabled:false}));
mock.module('@/components/AccountAccessStatus',()=>({AccountAccessStatus:Host}));
mock.module('@/constants/theme',()=>({C:{bg:'white'},FONT_ASSETS:{}}));
mock.module('@/components/LaunchExperience',()=>({LaunchExperience:()=>null}));
mock.module('@/components/MigrationNotice',()=>({MigrationNotice:()=>null}));
mock.module('expo-font',()=>({useFonts:()=>[true,null]}));
mock.module('expo-splash-screen',()=>({preventAutoHideAsync:async()=>{},hideAsync:async()=>{}}));
mock.module('expo-status-bar',()=>({StatusBar:()=>null}));
mock.module('react-native',()=>({View:Host,Text:Host,Pressable:Host}));
mock.module('react-native-gesture-handler',()=>({GestureHandlerRootView:Host}));
const {default:Root}=await import('../app/_layout');
let root:any;
async function render(){redirects=[];await act(async()=>{if(root)root.update(React.createElement(Root));else root=create(React.createElement(Root));});}
await render();assert.deepEqual(redirects,['/entry'],'cold empty guest must leave stale rehearsal route');
route='account-practice';await render();assert.deepEqual(redirects,['/entry'],'guest must escape account-only recovery');
route='continue-from-web';await render();assert.deepEqual(redirects,[],'login remains reachable');
route='privacy';await render();assert.deepEqual(redirects,[],'public disclosures remain reachable');
route='onboarding';store={...store,nativeJourneyStarted:true};await render();assert.deepEqual(redirects,[],'explicit new journey is not bounced');
route='rehearse';store={...store,profile:{persona:'woman-hope'},activePracticeSession:{id:'current'}};await render();assert.deepEqual(redirects,[],'active guest is not restarted');
auth={...auth,isGuestVisit:false,user:{id:'registered'}};store={...store,profile:null,activePracticeSession:null,nativeJourneyStarted:false};route='account-practice';await render();assert.deepEqual(redirects,[],'registered routing is unchanged');
await act(async()=>root.unmount());
console.log('PASS mounted root routing: fresh guest, active journey, login, public pages and registered owner');
