import {mock} from 'bun:test';import assert from 'node:assert/strict';
process.env.EXPO_PUBLIC_NATIVE_BILLING_ORIGIN='https://beforeyousayit.app';delete process.env.EXPO_PUBLIC_BYSI_BUILD_MODE;
const input=Uint8Array.from([73,68,51,4,0,255,128,1,2,3,4]);const writes:{uri:string,value:string}[]=[];let played=0,blobReads=0;
mock.module('react-native',()=>({Platform:{OS:'ios'}}));
const user={id:'synthetic-owner',is_anonymous:false,email_confirmed_at:'2026-01-01'};
const auth={getSession:async()=>({data:{session:{access_token:'synthetic',user}},error:null}),getUser:async()=>({data:{user},error:null}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})};
mock.module('../lib/supabase',()=>({supabase:{auth},authEnvironment:{url:'https://spvksnddzyvycfoefrcf.supabase.co'}}));
const {createNativeBilling}=await import('../lib/nativeBilling');
const nativeBilling=createNativeBilling({enabled:true,authUrl:'https://spvksnddzyvycfoefrcf.supabase.co',origin:'https://beforeyousayit.app',auth,fetch:async(url)=>{assert.equal(String(url),'https://beforeyousayit.app/api/native/tts');return new Response(input,{headers:{'content-type':'audio/mpeg'}})}});
mock.module('../lib/nativeBillingRuntime',()=>({nativeBilling}));
(globalThis as any).__DEV__=false;
Object.defineProperty(AbortSignal.prototype,'throwIfAborted',{value:undefined,configurable:true});
mock.module('../lib/normalFreeRuntime',()=>({requestNormalFree:async()=>({ok:true,status:200,headers:new Headers({'content-type':'audio/mpeg'}),arrayBuffer:async()=>input.buffer,blob:async()=>{blobReads++;throw Error("Creating blobs from 'ArrayBuffer' and 'ArrayBufferView' are not supported");}})}));
mock.module('expo-file-system/legacy',()=>({cacheDirectory:'file:///synthetic/',EncodingType:{Base64:'base64'},makeDirectoryAsync:async()=>{},writeAsStringAsync:async(uri:string,value:string)=>{writes.push({uri,value});},getInfoAsync:async()=>({exists:false}),deleteAsync:async()=>{},readDirectoryAsync:async()=>[]}));
mock.module('expo-audio',()=>({setAudioModeAsync:async()=>{},createAudioPlayer:({uri}:{uri:string})=>{assert.equal(uri,writes[0]?.uri);return {isLoaded:true,currentStatus:{isLoaded:true},volume:1,muted:false,addListener:()=>({remove(){}}),play(){played++;},pause(){},remove(){}};}}));
Response.prototype.blob=async()=>{blobReads++;throw Error("Creating blobs from ArrayBuffer is unsupported in the modeled native runtime")};
const {speakPaidPilotAudio,resetSpeech}=await import('../lib/voice');
const outcome=await speakPaidPilotAudio({voice_key:'hope_teacher',text:'Synthetic approved reply.'} as any);await resetSpeech();
assert.equal(outcome,'played','native TTS should reach player instead of unsupported Blob conversion');assert.equal(blobReads,0);assert.equal(played,1);assert.equal(writes.length,1);assert.deepEqual(Buffer.from(writes[0].value,'base64'),Buffer.from(input));assert(writes[0].uri.includes('synthetic-owner'));
nativeBilling?.dispose();
console.log('PASS actual paid transport -> speak -> native byte conversion -> owner cache -> modeled player. No on-device playback claim.');
