import {mock} from 'bun:test';
import {plugin} from 'bun';
import assert from 'node:assert/strict';
import React from 'react';
import {verifyComponentTestDeps} from '../scripts/component-test-deps';
const {create,act}=await import(verifyComponentTestDeps());
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
(globalThis as any).__DEV__=false;
globalThis.fetch=async()=>{throw Error('External network prohibited')};
plugin({name:'assets',setup(b){b.onLoad({filter:/\.(png|ttf)$/},()=>({contents:'export default 1',loader:'js'}))}});
const Host=(p:any)=>React.createElement('view',p,p.children);
mock.module('react-native',()=>({View:Host,Text:Host,ScrollView:Host,TextInput:Host,Pressable:Host,KeyboardAvoidingView:Host,ActivityIndicator:Host,Platform:{OS:'ios',select:(v:any)=>v.ios??v.default},StyleSheet:{create:(v:any)=>v,hairlineWidth:1},Alert:{alert(){}},Linking:{}}));
mock.module('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:0,bottom:0})}));
mock.module('lucide-react-native',()=>Object.fromEntries(['Check','ChevronRight','LockKeyhole','Mic','Play','RotateCcw','Square','Volume2','X'].map(x=>[x,()=>null])));
mock.module('@/components/ui',()=>Object.fromEntries(['Backdrop','Eyebrow','GlassCard','GhostButton','MicControl','PressCard','PrimaryButton','Reveal','StateDock','Thinking','tap'].map(x=>[x,Host])));
mock.module('@/components/PaidProductUI',()=>({ProductCard:Host,SectionLabel:Host,StatusPill:Host}));
mock.module('expo-router',()=>({useRouter:()=>({back(){},replace(){},push(){}}),useLocalSearchParams:()=>({day:'1',id:'unknown',lessonId:'unknown'})}));
mock.module('@/providers/store',()=>({useStore:()=>({activeScenarioRun:null,activePracticeSession:null,access:{},pilotDoneDays:[],completedPracticeIds:[],sessions:[],profile:null,drillProgress:{}})}));
mock.module('expo-file-system',()=>({File:class {exists=false;delete(){}}}));
mock.module('expo-file-system/legacy',()=>({deleteAsync:async()=>{}}));
mock.module('expo-crypto',()=>({randomUUID:()=>crypto.randomUUID()}));
mock.module('@/lib/purchases',()=>({trialEligibility: async () => 0, useIsPro:()=>false}));
mock.module('@/lib/ai',()=>Object.fromEntries(['evaluatePilotAttempt','nextPilotCounterpart','generateM1L1DynamicReply','generateApprovedRehearsalDynamicReply','generateDebrief','nextCounterpartTurn','drillRoundFeedback'].map(x=>[x,async()=>{throw Error('No provider')}])));
let generation=0,cancelled:number[]=[],resets=0;
const pending=new AbortController();
mock.module('@/lib/useDictation',()=>({useDictation:()=>{const captured=generation;const cancel=React.useCallback(async()=>{cancelled.push(captured);pending.abort()},[captured]);return {status:'transcribing',error:'',cancel,start:async()=>{},stop:async()=>null}}}));
mock.module('@/lib/voice',()=>({playPreparedPilotAudio:async()=>{},preparePaidPilotAudio:async()=>false,unlockAudioPlayback:async()=>{},useSpeech:()=>({status:'idle',phase:'idle'}),resetSpeech:async()=>{resets++},replaySpeech:async()=>{},stopSpeech:async()=>{},speakPaidPilotAudio:async()=>{},speakPaidPilotAudioToCompletion:async()=>{}}));
const {M1L1PaidPractice}=await import('../components/M1L1PaidPractice');
const {ScenarioPaidPractice}=await import('../components/ScenarioPaidPractice');
const {default:Module}=await import('../app/module/[day]');
const {M1_L1_CONVERSION}=await import('../lib/convertedLesson');
const scenario={id:'synthetic',title:'Synthetic',difficulty:'easy',goal:'Ask',counterpart:'Peer'};
const cases:any={m1:[M1L1PaidPractice,{requestedRunId:'missing',convertedLesson:M1_L1_CONVERSION,onReturnToDeck(){},onDiscard:async()=>{}}],scenario:[ScenarioPaidPractice,{scenario}],module:[Module,{}]};
const [Component,props]=cases[process.argv[2]??'scenario'];
let root:any;await act(async()=>{root=create(React.createElement(Component,props))});
const before=resets;generation=1;
await act(async()=>{root.update(React.createElement(Component,{...props}))});
assert.deepEqual(cancelled,[],'callback recreation must not cancel in-flight transcription');
assert.equal(pending.signal.aborted,false);assert.equal(resets,before,'callback recreation must not reset speech');
await act(async()=>{root.unmount()});
assert.equal(cancelled.length,process.argv[2]==='module'?3:1);assert.ok(cancelled.every(x=>x===1),'leave uses latest recorder callbacks');assert.equal(pending.signal.aborted,true);assert.equal(resets,before+1);
console.log(JSON.stringify({caller:process.argv[2],mounted:true,callbackRecreationPreservedPending:true,leaveCancelledLatest:true,externalDispatches:0}));
