import {mock} from 'bun:test';import assert from 'node:assert/strict';
process.env.EXPO_PUBLIC_BYSI_BUILD_MODE=process.argv[2]==='wrong-mode'?'':'staging-account';process.env.EXPO_PUBLIC_TTS_ENDPOINT='https://beforeyousayit.app/api/tts';process.env.EXPO_PUBLIC_STAGING_PAID_GENERATE_ENDPOINT=process.argv[2]==='missing'?'':'https://bysi-signup-staging.vercel.app/api/practice/generate';
(globalThis as any).__DEV__=true;
let authEvent:(event:string,s:any)=>void=()=>{};const user={id:'owner',is_anonymous:false,email_confirmed_at:'2026-01-01'};
mock.module('@/lib/supabase',()=>({authEnvironment:{staging:process.argv[2]!=='wrong-mode',url:'https://pqqxaklcburdxjfeolmd.supabase.co'},supabase:{auth:{getSession:async()=>({data:{session:{access_token:'aaa.bbb.ccc',user}},error:null}),getUser:async()=>({data:{user},error:null}),onAuthStateChange:(fn:typeof authEvent)=>{authEvent=fn;return {data:{subscription:{unsubscribe(){}}}};}}}}));
mock.module('react-native',()=>({Platform:{OS:'web'}}));mock.module('expo-audio',()=>({createAudioPlayer(){throw Error('unexpected native player');},setAudioModeAsync:async()=>{}}));
let played=0,readerStarted=false,readerAborted=false;const el={src:'',preload:'',currentTime:0,setAttribute(){},pause(){},play:async()=>{played++;}};
globalThis.document={createElement:()=>el} as unknown as Document;
globalThis.FileReader=class{result='data:audio/mpeg;base64,YQ==';onloadend?:()=>void;readAsDataURL(){readerStarted=true;if(process.argv[2]!=='logout')this.onloadend?.();}abort(){readerAborted=true;}} as unknown as typeof FileReader;
const seen:{url:string;init?:RequestInit}[]=[];globalThis.fetch=(async(url,init)=>{if(String(url).startsWith('blob:'))return new Response(new Blob(['synthetic'],{type:'audio/mpeg'}));seen.push({url:String(url),init});return String(url).endsWith('/tts')?new Response('synthetic-audio',{headers:{'content-type':'audio/mpeg'}}):Response.json({text:'Synthetic transcript.'});}) as typeof fetch;
const {speakPaidPilotAudio,resetSpeech,hasReplayableLine}=await import('@/lib/voice');const {transcribeRecording}=await import('@/lib/transcription');
const pending=speakPaidPilotAudio({audio_id:'qa-runtime-unique',voice_key:'adam_counterpart',text:'Exact displayed text'});
if(process.argv[2]==='logout'){for(let i=0;i<100&&!readerStarted;i++)await new Promise(r=>setTimeout(r,1));assert.ok(readerStarted);authEvent('SIGNED_OUT',null);assert.equal(await pending,'empty');assert.equal(readerAborted,true);assert.equal(played,0);assert.equal(hasReplayableLine(),false);}
else if(['missing','wrong-mode'].includes(process.argv[2]!)){assert.equal(await pending,'failed');assert.equal(played,0);assert.equal(seen.length,0);await assert.rejects(transcribeRecording('blob:qa','audio/mpeg','opener',{paidPractice:true}));assert.equal(seen.length,0);}
else{assert.equal(await pending,'played');assert.equal(played,1);assert.equal(await transcribeRecording('blob:qa','audio/mpeg','opener',{paidPractice:true}),'Synthetic transcript.');assert.deepEqual(seen.map(x=>x.url),['https://bysi-signup-staging.vercel.app/api/practice/tts','https://bysi-signup-staging.vercel.app/api/practice/transcribe']);assert.ok(seen.every(x=>new Headers(x.init?.headers).get('authorization')==='Bearer aaa.bbb.ccc'));assert.deepEqual(JSON.parse(seen[0]!.init!.body as string),{role:'adam',text:'Exact displayed text'});authEvent('SIGNED_OUT',null);assert.equal(hasReplayableLine(),false);}
await resetSpeech();
