import {test,expect} from 'bun:test';
import {createPaidGenerationTransport,PAID_STAGING_ENDPOINT} from '../lib/paidGeneration';
const owner='11111111-1111-4111-8111-111111111111';
test('initial same-owner session event during restoration does not cancel the first request',async()=>{
 const x=setup();let event!:Function;x.auth.onAuthStateChange=(cb:Function)=>{event=cb;return {data:{subscription:{unsubscribe(){}}}}};const original=x.auth.getSession;x.auth.getSession=async()=>{event('INITIAL_SESSION',{user:{id:owner}});return original()};const c=createPaidGenerationTransport(x.config)!;expect((await c.request({})).status).toBe(200);c.dispose();
});
test('a different owner in TOKEN_REFRESHED invalidates an in-flight response',async()=>{
 const x=setup();let event!:Function;x.auth.onAuthStateChange=(cb:Function)=>{event=cb;return {data:{subscription:{unsubscribe(){}}}}};let resolve!:Function;x.config.fetch=async()=>new Promise(r=>{resolve=r});const c=createPaidGenerationTransport(x.config)!;
 const pending=c.request({},100);await new Promise(r=>setTimeout(r,5));event('TOKEN_REFRESHED',{user:{id:'different-owner'}});resolve(Response.json({text:'Old owner'}));await expect(pending).rejects.toThrow();c.dispose();
});
function setup(){let listener:Function=()=>{};let token='a.b.c';const calls:any[]=[];const auth={async getSession(){return {data:{session:{access_token:token,user:{id:owner}}},error:null}},async getUser(jwt:string){return {data:{user:{id:owner,is_anonymous:false,email_confirmed_at:'2026-01-01'}},error:null}},onAuthStateChange(cb:Function){listener=cb;return {data:{subscription:{unsubscribe(){}}}}}};return {auth,calls,change(){listener('SIGNED_OUT',null)},refresh(){token='d.e.f'},config:{developmentBuild:true,staging:true,authUrl:'https://pqqxaklcburdxjfeolmd.supabase.co',endpoint:PAID_STAGING_ENDPOINT,auth,fetch:async(url:any,init:any)=>{calls.push({url,init});return Response.json({mode:'turn',text:'Exact fixture output'});}}};}
test('paid native transport pins endpoint and uses fresh bearer on every request',async()=>{const x=setup();const c=createPaidGenerationTransport(x.config);expect(c).not.toBeNull();expect((await c!.request({type:'rehearsal_turn'})).status).toBe(200);x.refresh();await c!.request({type:'free_rehearsal_result'});expect(x.calls.map(c=>c.init.headers.Authorization)).toEqual(['Bearer a.b.c','Bearer d.e.f']);expect(x.calls.every(c=>c.url===PAID_STAGING_ENDPOINT&&c.init.redirect==='error')).toBe(true);c!.dispose();});
test('unreviewed URLs and normal binaries never receive paid bearer',()=>{const x=setup();for(const override of [{endpoint:''},{endpoint:'https://beforeyousayit.app/api/generate'},{staging:false},{developmentBuild:false},{authUrl:'https://other.supabase.co'}])expect(createPaidGenerationTransport({...x.config,...override})).toBeNull();});
test('logout invalidates late response even if fetch ignores abort',async()=>{const x=setup();let resolve!:Function;x.config.fetch=async()=>new Promise(r=>{resolve=r});const c=createPaidGenerationTransport(x.config)!;const p=c.request({type:'rehearsal_turn'});await new Promise(r=>setTimeout(r,5));x.change();await expect(p).rejects.toThrow();resolve(Response.json({text:'Stale owner content'}));c.dispose();});
test('deadline includes stalled Auth and body; invalid confirmed owner never reaches network',async()=>{
 const x=setup();x.auth.getSession=async()=>new Promise(()=>{});const c=createPaidGenerationTransport(x.config)!;await expect(c.request({},5)).rejects.toThrow();expect(x.calls).toHaveLength(0);c.dispose();
 const y=setup();y.auth.getUser=async()=>({data:{user:{id:'other',is_anonymous:false,email_confirmed_at:'2026-01-01'}},error:null});const d=createPaidGenerationTransport(y.config)!;await expect(d.request({})).rejects.toThrow();expect(y.calls).toHaveLength(0);d.dispose();
 const z=setup();z.config.fetch=async()=>new Response(new ReadableStream({start(controller){controller.enqueue(new TextEncoder().encode('{'));}}));const e=createPaidGenerationTransport(z.config)!;await expect(e.request({},5)).rejects.toThrow();e.dispose();
});
