import {test,expect} from 'bun:test';
import {createPaidVoiceTransport,PAID_VOICE_ENDPOINTS} from '../lib/paidVoice';
const jwt='aaa.bbb.ccc',user={id:'owner',is_anonymous:false,email_confirmed_at:'2026-01-01'};
function fixture(send:typeof fetch){let cb:(event:string,s:any)=>void=()=>{};const auth={getSession:async()=>({data:{session:{access_token:jwt,user}},error:null}),getUser:async()=>({data:{user},error:null}),onAuthStateChange:(fn:typeof cb)=>{cb=fn;return {data:{subscription:{unsubscribe(){}}}};}};const transport=createPaidVoiceTransport({developmentBuild:true,staging:true,authUrl:'https://pqqxaklcburdxjfeolmd.supabase.co',endpoints:PAID_VOICE_ENDPOINTS,auth,fetch:send})!;return {transport,change:()=>cb('SIGNED_OUT',null),auth};}
test('paid voice sends fresh verified bearer and actual multipart, no generic endpoint or cookies',async()=>{const seen:any[]=[];const {transport}=fixture((async(url,init)=>{seen.push({url,init});return new Response(new Uint8Array(String(url).endsWith('/tts')?180000:20),{headers:{'content-type':'audio/mpeg'}});}) as typeof fetch);const r=await transport.request('tts',{text:'Hello',role:'hope'});expect((await r.arrayBuffer()).byteLength).toBe(180000);const body=new FormData();body.append('turn','opener');await transport.request('transcribe',body);expect(seen.map(v=>v.url)).toEqual([PAID_VOICE_ENDPOINTS.tts,PAID_VOICE_ENDPOINTS.transcribe]);expect(seen[0].init.headers.Authorization).toBe('Bearer '+jwt);expect(seen[0].init.credentials).toBe('omit');expect(seen[1].init.body).toBe(body);expect(seen[1].init.headers['Content-Type']).toBeUndefined();transport.dispose();});
test('paid voice invalidates account during body and bounds stalled transport',async()=>{let ready!:()=>void;const arrived=new Promise<void>(r=>ready=r);let cancel=false;const f=fixture((async()=>{ready();return new Response(new ReadableStream({cancel(){cancel=true;}}));}) as typeof fetch);const result=f.transport.request('tts',{text:'Hi',role:'adam'},500).catch(()=>null);await arrived;await new Promise(r=>setTimeout(r,10));f.change();expect(await result).toBeNull();expect(cancel).toBe(true);f.transport.dispose();});
test('deadline before Auth resolves never dispatches a late provider request',async()=>{let release!:(v:any)=>void;let calls=0;const fx=fixture((async()=>{calls++;return new Response('bad');}) as typeof fetch);fx.auth.getSession=()=>new Promise(r=>release=r);const result=fx.transport.request('tts',{text:'hi',role:'hope'},10).catch(()=>null);await new Promise(r=>setTimeout(r,20));expect(await result).toBeNull();release({data:{session:{access_token:jwt,user}},error:null});await new Promise(r=>setTimeout(r,10));expect(calls).toBe(0);fx.transport.dispose();});
test('account invalidation clears downstream playback even after network completion',async()=>{let invalidated=0;const fx=fixture(fetch);const t=createPaidVoiceTransport({developmentBuild:true,staging:true,authUrl:'https://pqqxaklcburdxjfeolmd.supabase.co',endpoints:PAID_VOICE_ENDPOINTS,auth:fx.auth,onInvalidate:()=>{invalidated++;},fetch:(async()=>new Response('audio')) as typeof fetch})!;await t.request('tts',{text:'hi',role:'hope'});fx.change();expect(invalidated).toBe(1);t.dispose();fx.transport.dispose();});
test('native non-streaming Response retains audio bytes instead of producing empty speech',async()=>{const data=new Uint8Array([1,2,3,4]);const fx=fixture((async()=>({status:200,headers:new Headers({'content-type':'audio/mpeg'}),arrayBuffer:async()=>data.buffer})) as unknown as typeof fetch);const r=await fx.transport.request('tts',{text:'hi',role:'hope'});expect(new Uint8Array(await r.arrayBuffer())).toEqual(data);fx.transport.dispose();});
test('paid voice gates exact build project and endpoint pair',()=>{const {transport,auth}=fixture(fetch);for(const patch of [{staging:false},{developmentBuild:false},{authUrl:'https://spvksnddzyvycfoefrcf.supabase.co'},{endpoints:{...PAID_VOICE_ENDPOINTS,tts:'https://beforeyousayit.app/api/tts'}}])expect(createPaidVoiceTransport({developmentBuild:true,staging:true,authUrl:'https://pqqxaklcburdxjfeolmd.supabase.co',endpoints:PAID_VOICE_ENDPOINTS,auth,...patch})).toBeNull();transport.dispose();});
