import {mock} from 'bun:test';
import assert from 'node:assert/strict';
import React from 'react';
import {verifyComponentTestDeps} from '../scripts/component-test-deps';
const {create,act}=await import(verifyComponentTestDeps());
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
const Host=(p:any)=>React.createElement('view',p,p.children);
mock.module('react-native',()=>({View:Host,Text:Host,ActivityIndicator:Host,StyleSheet:{create:(s:any)=>s},Linking:{openURL:async()=>{}}}));
mock.module('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:59,bottom:34})}));
mock.module('@/constants/theme',()=>({C:{bg:'field'},T:{body:{}}}));
mock.module('@/components/ui',()=>({Backdrop:Host}));
let ui:any;
mock.module('@/components/AnswerFirstOnboarding',()=>({AnswerFirstOnboarding:(p:any)=>{ui=p;return <Host/>;},AnswerButton:Host}));
mock.module('@/components/NativeBillingGate',()=>({NativeBillingGate:Host}));
let user:any=null,access=false,params:any={},claims=0,buys=0,permission=0,status='pending';
const routes:any[]=[];
mock.module('expo-router',()=>({useRouter:()=>({push:(r:any)=>routes.push(r),replace:(r:any)=>routes.push(r)}),useLocalSearchParams:()=>params}));
mock.module('@/providers/auth',()=>({useAuth:()=>({user})}));
mock.module('@/lib/nativeBillingRuntime',()=>({normalBillingEnabled:true}));
mock.module('@/lib/purchaseFirstPolicy',()=>({purchaseFirstEnabled:true,usePurchaseFirstPolicy:()=>({data:true,refetch:async()=>{}})}));
const answers={diff:'clarity',ctx:'work',rec:'bury'};
let claimReads=0,readFailures=0,storedAnswers:any=answers;
mock.module('@/lib/answerFirstStorage',()=>({readAnswerFirst:async()=>storedAnswers,claimAnswerFirst:async()=>{claimReads++;if(readFailures-->0)throw Error('Synthetic storage failure');return storedAnswers;},writeAnswerFirst:async()=>{}}));
const product={identifier:'byis_pro_monthly_5',priceString:'$11.99',subscriptionPeriod:'P1M',introPrice:{price:0,period:'P1W',cycles:1}};
const info={entitlements:{active:{pro:{isActive:true,productIdentifier:product.identifier,store:'APP_STORE',periodType:'TRIAL',willRenew:true,expirationDate:new Date(Date.now()+7*86400000).toISOString()}}}};
mock.module('@/lib/purchases',()=>({hasPro:()=>true,trialEligibility:async()=>2,useIsPro:()=>access,useCustomerInfo:()=>({data:info,refetch:async()=>{}}),useNativeServerAccess:()=>({refetch:async()=>{}}),useOfferings:()=>({data:{current:{monthly:{product}}},isLoading:false,isError:false}),usePurchasePackage:()=>({mutateAsync:async()=>{buys++;return {status:'purchased'};}}),useRestorePurchases:()=>({mutateAsync:async()=>false}),usePreAccountPurchase:()=>({mutateAsync:async()=>{buys++;return {status:'account_required'};}}),useClaimPreAccountPurchase:()=>({mutateAsync:async()=>{claims++;return status;}})}));
mock.module('@/lib/trialReminder',()=>({enableTrialReminder:async()=>{permission++;return 'enabled';},syncTrialReminder:async()=> 'scheduled'}));
const {default:Route}=await import('../app/answer-onboarding');
let root:any;await act(async()=>{root=create(<Route/>);});
assert.equal(ui.initialScreen,'account');assert.equal(ui.accountRequired,true);assert.equal(permission,0);
await act(async()=>ui.onAccount('signup',answers));assert.equal(routes.pop().params.mode,'signup');assert.equal(buys,0);
await act(async()=>root.unmount());user={id:'owner-a'};params={source:'account-return'};
await act(async()=>{root=create(<Route/>);});assert.equal(claims,1);assert.equal(ui.confirmation,'pending');assert.equal(ui.access,false);assert.equal(permission,0);
await act(async()=>root.update(<Route/>));assert.equal(claims,1,'rerenders do not repeatedly claim');
await act(async()=>ui.onPractice(answers));assert.equal(routes.length,0);
status='linked';access=true;await act(async()=>ui.onCheckAccess());await act(async()=>root.update(<Route/>));assert.equal(ui.initialScreen,'setup');assert.equal(permission,1);assert.equal(buys,0);
await act(async()=>ui.onPractice(answers));assert.equal(routes.pop(),'/first-practice');
await act(async()=>root.unmount());params={source:'resume'};
await act(async()=>{root=create(<Route/>);});assert.equal(ui.confirmation,'ready');assert.equal(ui.initialScreen,'setup');assert.equal(permission,2,'resumed verified trial schedules without same-session confirmation');
await act(async()=>root.unmount());
params={source:'account-return'};readFailures=1;
const beforeReads=claimReads;
await act(async()=>{root=create(<Route/>);});
const retry=root.root.findAllByType('view').find((v:any)=>v.props.label==='Retry loading');
assert.ok(retry,'failed account-return load must offer retry');
await act(async()=>retry.props.onPress());
assert.equal(claimReads,beforeReads+2,'retry must repeat account-return claim, not navigate away from its intent');
assert.deepEqual(ui.initialAnswers,answers);
assert.equal(root.root.findAllByType('view').filter((v:any)=>v.props.label==='Retry loading').length,0);
assert.equal(routes.length,0,'retry must not change the account-return route');
await act(async()=>root.unmount());
storedAnswers={};access=false;params={source:'account-return'};
await act(async()=>{root=create(<Route/>);});
const control=(label:string)=>root.root.findAllByType('view').find((v:any)=>v.props.label===label);
assert.ok(control('Restore purchases'),'signed-in account without local answers must reach restore, not welcome');
assert.ok(!control('Continue to Home'),'unverified access must not enable paid handoff');
await act(async()=>control('Restore purchases').props.onPress());
assert.equal(buys,0,'restore must never repurchase');
access=true;await act(async()=>root.update(<Route/>));
await act(async()=>control('Continue to Home').props.onPress());assert.equal(routes.pop(),'/(tabs)');
await act(async()=>root.unmount());
storedAnswers=answers;params={source:'account-login'};
await act(async()=>{root=create(<Route/>);});
assert.ok(control('Continue to Home'),'returning login with saved answers must not repeat onboarding');
await act(async()=>root.unmount());params={};
await act(async()=>{root=create(<Route/>);});
assert.ok(control('Restore purchases'),'persisted registered session must not show signed-out welcome');
await act(async()=>root.unmount());
console.log('PASS purchase-first controller: account return, missing-answer restore, returning login and persisted session recovery. SDK/Auth/backend/UI simulated; not device acceptance.');
