import {mock} from 'bun:test';import {plugin} from 'bun';import assert from 'node:assert/strict';import React from 'react';import {verifyComponentTestDeps} from '../scripts/component-test-deps';
const {create,act}=await import(verifyComponentTestDeps());(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;plugin({name:'assets',setup(b){b.onLoad({filter:/\.(png|ttf)$/},()=>({contents:'export default 1',loader:'js'}));}});
const Host=(p:any)=>React.createElement('host',p,p.children);
mock.module('react-native',()=>({AppState:{addEventListener:()=>({remove(){}})},ScrollView:Host,Text:Host,View:Host,Pressable:(p:any)=>React.createElement('button',p,p.children),StyleSheet:{create:(v:any)=>v},Platform:{OS:'web',select:(v:any)=>v.web??v.default}}));
mock.module('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:0,bottom:0})}));
let route:any=null;const router={replace:(v:any)=>{route=v;},push:(v:any)=>{route=v;}};mock.module('expo-router',()=>({useRouter:()=>router}));
mock.module('@/components/ui',()=>({PrimaryButton:(p:any)=>React.createElement('button',p,p.label)}));
mock.module('@/components/OriginalFollowThrough',()=>({OriginalFollowThrough:()=>null}));
mock.module('@/components/AccountLogout',()=>({AccountLogout:()=>null}));
mock.module('@/components/PrivateWebResultPresentation',()=>({PrivateWebResultPresentation:(p:any)=>React.createElement('host',null,'RESULT:',p.record.marker)}));
mock.module('@/lib/purchases',()=>({useNativeServerAccess:()=>({data:false,isPending:false,isFetching:false,isError:false,refetch:async()=>{}})}));
mock.module('@/lib/nativeBillingRuntime',()=>({nativeBilling:null}));
mock.module('@/lib/launchCurriculum',()=>({nextLaunchDeck:()=>null}));
const newest={sessionId:'11111111-1111-4111-8111-111111111111',source:'normal-native-free',capturedAt:'2026-09-15T12:00:00.000Z',expiresAt:null,privateResult:{marker:'newest'}};
const older={sessionId:'22222222-2222-4222-8222-222222222222',source:'normal-native-free',capturedAt:'2026-09-14T12:00:00.000Z',expiresAt:null,privateResult:{marker:'older'}};
const calls:string[]=[];const service={latest:async()=>newest,history:async()=>[newest,older],restore:async(id:string)=>{calls.push('restore:'+id);return id===older.sessionId?older:newest;},delete:async()=>({deleted:1}),deleteAll:async()=>({deleted:121}),invalidate(){},dispose(){}};mock.module('@/providers/auth',()=>({useAuth:()=>({user:{id:'owner'},normalResults:service,isLoggingOut:false,practiceOwner:{key:'owner'}})}));
mock.module('@/providers/store',()=>({useStore:()=>({hydrated:true,convertedLessonProgress:[],moduleCloseProgress:[]})}));
const {default:Saved}=await import('../app/saved-result');let root:any;const flush=async()=>{for(let i=0;i<6;i++)await act(async()=>{await new Promise(r=>setTimeout(r,0));});};const text=()=>JSON.stringify(root.toJSON());
const press=async(label:string)=>{const b=root.root.findAllByType('button').find((n:any)=>n.props.label===label);assert.ok(b,label);await act(async()=>{await b.props.onPress();});await flush();};
await act(async()=>{root=create(React.createElement(Saved));});await flush();assert.ok(text().includes('newest'));assert.ok(text().includes('Saved result history'));await press('Open saved result from 9/14/2026');assert.ok(text().includes('older'));assert.ok(calls.includes('restore:'+older.sessionId));await press('Delete all saved results');assert.ok(text().includes('121 saved results deleted.'));assert.equal(route,null);await act(async()=>root.unmount());console.log('PASS mounted saved-result history pagination/open/delete-all surface; synthetic service, actual component controls');
