import {mock} from 'bun:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
mock.module('react-native',()=>({Platform:{OS:'ios'}}));
mock.module('expo-file-system/legacy',()=>({cacheDirectory:'cache/',getInfoAsync:async()=>({exists:false})}));
const disk=new Map<string,string>();let fail=false;
const host={getItem:async(k:string)=>disk.get(k)??null,setItem:async(k:string,v:string)=>{disk.set(k,v);},removeItem:async(k:string)=>{disk.delete(k);},getAllKeys:async()=>[...disk.keys()],multiRemove:async(keys:string[])=>{for(const k of keys)disk.delete(k);}};
const secure=new Map<string,string>();let dropReceipt=false;
const key=(k:string,o:any)=>`${o?.keychainService??'default'}:${k}`;
mock.module('expo-secure-store',()=>({isAvailableAsync:async()=>true,AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY:4,getItemAsync:async(k:string,o:any)=>secure.get(key(k,o))??null,setItemAsync:async(k:string,v:string,o:any)=>{assert.ok(Buffer.byteLength(v)<=1800);if(!dropReceipt||!k.includes('accountDeletion.receipt'))secure.set(key(k,o),v);},deleteItemAsync:async(k:string,o:any)=>{if(fail)throw Error('disk');secure.delete(key(k,o));}}));
mock.module('expo-crypto',()=>({CryptoDigestAlgorithm:{SHA256:'SHA256'},randomUUID,digestStringAsync:async(_:string,v:string)=>createHash('sha256').update(v).digest('hex')}));
mock.module('@react-native-async-storage/async-storage',()=>({default:host}));
mock.module('@/lib/baselineAudio',()=>({baselineFileName:(id:string)=>`${id.replace(/[^a-zA-Z0-9_-]/g,'')||'session'}.m4a`,listBaselineAudioFileNamesStrict:async()=>[],deleteBaselineAudioStrict:async()=>{}}));
const url='https://spvksnddzyvycfoefrcf.supabase.co';
mock.module('@/lib/supabase',()=>({authEnvironment:{url,keychainService:'beforeyousayit.supabase',staging:false},supabase:null}));
const {createGuestContinuationRuntime}=await import('../lib/guestContinuationRuntime');
const {createOwnerPracticeStorage}=await import('../lib/ownerPracticeStorage');
const {cleanupDeletedAccountOwner,accountDeletionReceiptStore}=await import('../lib/accountLifecycleRuntime');
dropReceipt=true;await assert.rejects(accountDeletionReceiptStore.save({ownerId:'A',secret:'a'.repeat(64),digest:'b'.repeat(64)}),'silent receipt write must fail before dispatch');dropReceipt=false;
const environment=JSON.stringify([url,'beforeyousayit.supabase']);
const continuation=createGuestContinuationRuntime(host,'ios',environment);
const owner=createOwnerPracticeStorage(host,`${url}:A`);
await owner.setItem('cc.activePracticeSession.v1',JSON.stringify({id:'fixture',text:'x'.repeat(7000)}));
await continuation.begin(owner,'fixture');assert.ok(secure.size>3);
await cleanupDeletedAccountOwner('B');assert.ok(secure.size>3,'B cleanup preserves A');
fail=true;await assert.rejects(cleanupDeletedAccountOwner('A'),'SecureStore failure must surface');
fail=false;await cleanupDeletedAccountOwner('A');assert.equal(secure.size,0,'all actual secure chunks removed');
assert.equal(await host.getItem(`bysi.owner.v1:${encodeURIComponent(url+':A')}:cc.activePracticeSession.v1`),null);
console.log('secure runtime owner erasure: real continuation namespace, chunks, failure retry and B isolation passed');
