import { mock } from "bun:test";
import { plugin } from "bun";
import assert from "node:assert/strict";
import React from "react";
import { createNativeSessionStarter, type NativeSessionResult } from "../lib/nativeAuth";
import { describeAuthConfiguration } from "../lib/authConfigurationDiagnostic";
import { verifyComponentTestDeps } from "../scripts/component-test-deps";

plugin({ name: "setup-diagnostic-host-assets", setup(b) { b.onLoad({ filter: /\.(png|ttf)$/ }, () => ({ contents: "export default 1", loader: "js" })); } });
const { create, act } = await import(verifyComponentTestDeps());
(globalThis as any).IS_REACT_ACT_ENVIRONMENT = true;
const Host = (p: any) => React.createElement("host", p, p.children);
mock.module("react-native", () => ({ View: Host, Text: Host, ScrollView: Host, Platform: { OS: "ios", select: (v: any) => v.ios ?? v.default }, StyleSheet: { create: (v: any) => v } }));
mock.module("react-native-svg", () => ({ default: Host, Circle: Host, Path: Host, Rect: Host }));
mock.module("react-native-safe-area-context", () => ({ useSafeAreaInsets: () => ({ top: 0, bottom: 0 }) }));
mock.module("@/components/ui", () => ({ Backdrop: () => null, Reveal: Host, GhostButton: (p: any) => React.createElement("button", p, p.label), PrimaryButton: (p: any) => React.createElement("button", p, p.label) }));
mock.module("@/components/AccountLogout", () => ({ AccountLogout: () => null }));
mock.module("@/providers/store", () => ({ useStore: () => ({ activePracticeSession: null }) }));
let route: string | null = null;
let attempts = 0;
let start = createNativeSessionStarter(null);
mock.module("@/providers/auth", () => ({ useAuth: () => ({ isAuthLoading: false, session: null, startNativeSession: async () => { attempts++; return start(); } }) }));
mock.module("expo-router", () => ({ useRouter: () => ({ replace: (value: string) => { route = value; }, push: (value: string) => { route = value; } }) }));
const report = describeAuthConfiguration({ developmentBuild: false, nativeStagingBuild: false, applicationId: "app.rork.8fc4qwsqaurkxk0pimyvx" }, null, { version: "1.0.0", build: "24" });
mock.module("@/lib/supabase", () => ({ authConfigurationDiagnostic: report }));
let copied: string | null = null;
let copyOutcome: "success" | "false" | "throw" = "success";
mock.module("expo-clipboard", () => ({ setStringAsync: async (text: string) => {
  if (copyOutcome === "throw") throw new Error("private-error-canary");
  if (copyOutcome === "false") return false;
  copied = text;
  return true;
} }));
const {LegacyEntryScreen:Entry} = await import("../app/entry");
let root: any;
await act(async () => { root = create(React.createElement(Entry)); });
const screen = (): string => JSON.stringify(root.toJSON());
const button = (label: string) => root.root.findAllByType("button").find((b: any) => b.props.label === label);
assert.ok(!screen().includes("BYSI setup diagnostic"));
assert.equal(copied, null, "never copy automatically");
await act(async () => { await button("Get started").props.onPress(); });
assert.equal(route, null, "diagnostics must not bypass setup");
assert.equal(attempts, 1);
assert.ok(screen().includes("configuration/unavailable"));
assert.ok(screen().includes("Normal URL: missing"));
assert.ok(screen().includes("Normal key: missing"));
assert.ok(screen().includes("Installed app: 1.0.0 (24)"));
assert.equal(copied, null);
await act(async () => { await button("Copy setup details").props.onPress(); });
assert.equal(copied, report);
assert.equal(attempts, 1, "copying must not retry authentication");
assert.ok(screen().includes("Copied. Paste the details into our chat."));
for (const outcome of ["false", "throw"] as const) {
  copyOutcome = outcome;
  await act(async () => { await button("Copy setup details").props.onPress(); });
  assert.ok(screen().includes("Couldn’t copy. Take a screenshot"));
  assert.ok(!screen().includes("private-error-canary"));
  assert.ok(!screen().includes("Copied. Paste"));
}
start = async (): Promise<NativeSessionResult> => ({ success: false, message: "Setup code: guest-signin/rejected." });
await act(async () => { await button("Get started").props.onPress(); });
assert.ok(!screen().includes("BYSI setup diagnostic"), "do not label a provider rejection as missing configuration");
assert.equal(route, null);
start = async (): Promise<NativeSessionResult> => ({ success: true, session: { access_token: "synthetic", user: { id: "fixture-guest", is_anonymous: true } } as any });
await act(async () => { await button("Get started").props.onPress(); });
assert.equal(route, "/onboarding");
assert.ok(!screen().includes("Setup details"));
await act(async () => { root.unmount(); });
console.log("PASS actual entry diagnostics, user-initiated copy, copy-failure recovery, and unchanged failure/success navigation. Synthetic native hosts only.");
