import {mock} from 'bun:test';
import assert from 'node:assert/strict';
import React from 'react';
const {verifyComponentTestDeps}=await import('../scripts/component-test-deps');
const {create,act}=await import(verifyComponentTestDeps());
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
let user:any=null,genericLogouts=0,scopedLogouts:string[]=[];let clearLocal:(owner:string)=>Promise<void>;
let release!:()=>void;const held=new Promise<void>(resolve=>release=resolve);
const Host=(p:any)=>React.createElement('host',p,p.children);
mock.module('expo-router',()=>({useRouter:()=>({back(){}}),useFocusEffect:()=>{}}));
mock.module('react-native',()=>({Platform:{OS:'ios',select:(value:any)=>value.ios??value.default},View:Host,Text:Host,ScrollView:Host,StyleSheet:{create:(v:any)=>v},AppState:{addEventListener:()=>({remove(){}})},Linking:{openURL:async()=>{}}}));
mock.module('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({top:0,bottom:0})}));
mock.module('lucide-react-native',()=>({CreditCard:()=>null}));
mock.module('@/constants/theme',()=>({C:{},GUTTER:16,T:{body:{},caption:{}},font:{bold:'synthetic'}}));
mock.module('@/components/PaidProductUI',()=>({PaidHeader:()=>null}));
mock.module('@/components/ui',()=>({Backdrop:()=>null,GhostButton:Host}));
mock.module('@/components/AccountLifecycleControls',()=>({AccountDeletionControls:()=>null,AccountDeletionStatusControls:(p:any)=>{clearLocal=p.clearLocal;return null;}}));
mock.module('@/lib/purchases',()=>({trialEligibility: async () => 0, PRO_ENTITLEMENT:'pro',useCustomerInfo:()=>({data:null})}));
mock.module('@/lib/accountLifecycleRuntime',()=>({cleanupDeletedAccountOwner:async(owner:string)=>{assert.equal(owner,'A');await held;}}));
mock.module('@/providers/auth',()=>({useAuth:()=>({user,logout:async()=>{genericLogouts++;return {success:true};},logoutDeletedOwner:async(owner:string)=>{scopedLogouts.push(owner);assert.equal(user.id,'B');return {success:true};}})}));
const {default:Delete}=await import('../app/delete-account');
let root:any;await act(async()=>{root=create(React.createElement(Delete));});
let pending!:Promise<void>;await act(async()=>{pending=clearLocal('A');});
user={id:'B'};await act(async()=>root.update(React.createElement(Delete)));
release();await act(async()=>await pending);
assert.equal(genericLogouts,0,'late signed-out A cleanup must not invoke generic logout after B signs in');
assert.deepEqual(scopedLogouts,['A'],'receipt cleanup must use the AuthProvider exact-owner SDK logout boundary');
await act(async()=>root.unmount());
console.log('PASS signed-out deletion callback preserves later B and uses exact-owner Auth boundary');
